### ISSUE TITLE
Allow user to override keybindings in comments and/or strings

### ISSUE THREAD

**Issue by crispinb** [BetterThanTomorrow/calva#1023]
Many* users report that they prefer default text language mode keyboard shortcuts for use within comments and strings. They could configure this for themselves if calva made 'inString' and 'inComment' when-contexts available.

(* OK, one user)

**Comment by crispinb** [comment]
I'm willing to have a stab at a PR for this, but don't know much about the VSCode extension API or execution model, so I'll have to read up a bit & scan the calva codebase. In the meantime I could do with some guidance for starting points.

As far as I can see from[ the docs](https://code.visualstudio.com/api/references/when-clause-contexts) and [one example from Microsoft](https://github.com/microsoft/vscode/blob/349e31fee9603711ddabfe4c8cb6fb66b72e28f3/extensions/git/src/main.ts#L43), it involves calling a vscode 'setContext' command to toggle the newly added contexts.

The initial questions that arise for me are:

- where do the relevant events come from?
- where will the code for these new contexts go?

**Comment by PEZ** [comment]
I think the relevant event is `vscode.window.onDidChangeTextEditorSelection` (see [`vscode.window`](https://code.visualstudio.com/api/references/vscode-api#window))

There is probably some things to consider so that it is the current active editor that the event is about. And also what should happen when the user activates a document.

The way to examine the code structure of the editor cursor's location is to use a Calva `TokenCursor`. You can create a token cursor for the current selection of a document if you have a reference the document and know the location. The event has a reference to the editor where the event fired and also to the new selection. From the editor you can get the document.

We do something similar here:

https://github.com/BetterThanTomorrow/calva/blob/dev/src/results-output/results-doc.ts

A `LispTokenCursor` instance (which is what you'll get) has a method for checking if the cursor is within a string. You might want to add a method for checking if we're in a comment (if there isn't one already, I don't remember). The methods `getToken()` and `getPrevToken()` should take you quite far, I think...

You can start by adding the event subscription in an anonymous function right in `src/extension.ts`, and we can figure out later where we want to move the implementation.

I hope I am making some little sense here? 😄

**Comment by bpringe** [comment]
Another thing that might help is placing a breakpoint in the code after getting/creating the token cursor, and calling methods on it in the Debug Console to get a feel for how it works.

**Comment by crispinb** [comment]
Thanks guys that all makes sense & should be helpful.
