### ISSUE TITLE
Paredit kill right

### ISSUE THREAD

**Issue by clyfe** [BetterThanTomorrow/calva#1024]
Cont'd from #380.  

Emacs paredit-kill effects in slightly different ways than either Calva's kill sexp or kill list.

In all examples that follow, killListForward outcome would be `(a|)`.  
Whereas paredit-kill has different behavior in each (it's more granular in its effects).

### Example 1 - s-expresions

```clojure
(a| b (c
       d) e)
```
\+ paredit-kill = (expressions starting on the current line past the cursor are killed)

```clojure
(a| e)
````

### Example 2 - comments

```clojure
(a| ;; comment
  e)
```

\+ paredit-kill = (comment killed)

```clojure
(a|
   e)
````

### Example 3 - newline

```clojure
(a|
  e)
```

\+ paredit-kill = (newline killed)

```clojure
(a| e)
````

**Comment by PEZ** [comment]
I like this!

I think that this is how VS Code's command **Delete All Right** should work in structural context. Well, if it kills to end of list when used from after example 3, at least: 

```clojure
(a| e)
=>
(a|)
```

We could consider binding the default shortcut for **Delete All Right** (`ctrl+k` on Mac) to this command when Paredit `strict` mode is on, and leave it default unbound otherwise.

I think the command could be named `paredit.killForward`. It is a bit unfortunate that these commands are named `kill` since it brings expectations about a kill ring, but let's keep it consistently wrong. 😑 

Question. What should happen here?

```clojure
(a b (c |d)
  e)
```

Maybe this:

```clojure
(a b (c |)
  e)
```

And from there, this:

```clojure
(a b |e)
```

Not sure. We could also refuse to kill anything...

**Comment by bpringe** [comment]
I don't think the expression should ever kill outside the current list. So if run here, nothing should happen. Just my 2 cents.

```clojure
(a b (c |)
  e)
```

**Comment by clyfe** [comment]
Generally "do [what emacs does](http://mumble.net/~campbell/emacs/paredit/paredit.el)" is a good orientation map, I'm sure they're way ahead with analyzing how & why.

**Comment by PEZ** [comment]
Yes, I tried this in Emacs now. It behaves as `killListForward` when there is no newline before the closing bracket. Makes sense.

**Comment by Kryptos-FR** [comment]
Could you consider changing the keyboard shortcut to something else than `Ctrl+K`. That key combination is already used by a lot of other shortcuts in VS Code, including (un)commenting code out (`Ctrl+K, Ctrl+C`, and `Ctrl+K, Ctrl+U`), collapsing code (`Ctrl+K, [1-9]`), etc.

Updating to that latest version of Calva killed my muscle memory/programming habit. And I'm sure it is also confusing to a lot of people.

Suggestion: replace the default with `Ctrl+K, K`.

**Comment by PEZ** [comment]
We're sorry about that. It's being tracked in #1356 and being worked on in #1358.
