### ISSUE TITLE
"ctrl+alt+c i" does not work in Ubuntu 20.04 (Kubuntu dist)

### ISSUE THREAD

**Issue by SockworkOrange** [BetterThanTomorrow/calva#1055]
According to the doc that key combination is supposed to instrument functions for debug - but it doesn't seem to have any affect in my VS Code. Every other command seems to work (alt + enter, placing #dbg / #break etc.).

**Comment by bpringe** [comment]
Hello. What are your repro steps for this? I'm guessing:

1. Connect to a repl / jack-in
2. Load file
3. Run `ctrl+alt+c i` with the cursor on a function to instrument
4. What happens here? 

I'm guessing you don't see the visual indication (blue lines on top and bottom of the symbol) that the function is instrumented. If you then call the function, the debugger does not start and break inside the function?

It's also worth checking the developer console for errors. (Help -> Toggle Developer Tools -> Console tab)

If you can provide an example function for which this isn't working so that I can try it out, that would help too. Thanks.

**Comment by bpringe** [comment]
I've now seen the Slack convo about this, and from what another user said, the instrumentation still works, it's just that the decorations are broken. I'll be digging into this soon. Seems it's not just a single OS issue as I believe the other user experienced it on Windows.

Edit: This also seems to be related to the latest vscode update.

**Comment by bpringe** [comment]
If anyone wants to try to debug this before I can get to it, the relevant code is in `debugger/decorations.ts`. The issue/fix probably lies in the `update` or `render` function.

**Comment by SockworkOrange** [comment]
actually no - to me at least it doesn't seem like just a decorator issue.
Tried to reproduce now with the following form:

```clojure
(ns debugging)

(defn chika [a b c]
  (println a)
  (println b)
  (println c) 
  c)

(chika 3 5 7)
```

does not work:
1. Evaluated the form with "alt+enter" - works
2. when cursor is on the function, clicked "ctrl+alt+c+i" - no decoration
3. executed the call to function with "alt+enter" - returns 7

works:
1. added #dbg to the function and evaluated with "alt+enter"
3. breaks in (println a)

**Comment by bpringe** [comment]
Ah I see. Thanks for the repro case!

**Comment by bpringe** [comment]
The decorations and debugging are working for me with the above example in Manjaro Linux on VS Code 1.54.1.

Can you tell me after reproducing the issue, do you see any errors in the dev console? Help -> Toggle Developer Tools -> Console tab

I'm going to test this in my Windows VM since we had a report that just decorations wasn't working there, which may or may not be related to this.

**Comment by bpringe** [comment]
Also, is this a lein project or deps.edn? Maybe there is some difference there, though that seems odd.

**Comment by bpringe** [comment]
Info from Eric Uitbeijerse on Slack who also had this issue, although for him just the decorations were not working. The debugger still worked. Peter has also seen the decorations not work but the debugger still work, and I think that was on MacOS.

Version: 1.54.1 (user setup)
Commit: f30a9b73e8ffc278e71575118b6bf568f04587c8
Date: 2021-03-04T22:38:31.419Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by SockworkOrange** [comment]
per your questions - 
1. This is a lein project
2. No errors in the console tab (in the developer tools)

If needed, we can schedule a zoom meeting and I'll show the behaviour live:)

**Comment by bpringe** [comment]
Sure, I'll message you on Slack.

**Comment by bpringe** [comment]
@SockworkOrange Any update on this issue? See if version 2.0.182 fixes your issue. (Not sure why it would, but it's worth a try.)

**Comment by bpringe** [comment]
Closing this since there's been no response for a while, and we've received no other reports. If this is still broken for you, please reopen the issue.
