### ISSUE TITLE
Auto-generated namespaces not working

### ISSUE THREAD

**Issue by brancusi** [BetterThanTomorrow/calva#1060]
Using the re-frame lein template.

### Reproduce
1. `lein new re-frame test-app`

### Video overview
https://www.loom.com/share/4ed8d11315a14e28b4603eeb173ae799

### System
1. OSX 10.15.7
2. VS Code 1.54.1

Thank you

**Comment by bpringe** [comment]
Thanks for taking the time to report this and make the video. We probably should move to using the clojure-lsp feature for this.

**Comment by bpringe** [comment]
Hey @brancusi, would you mind trying out the VSIX from the linked PR and tell me if it solves your issue? https://12365-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.183-use-clojure-lsp-add-ns-feature-309fd169.vsix

I started to try to reproduce your issue, but the template that `lein new re-frame <project>` creates doesn't include a shadow-cljs.edn file (not sure if it should), so I was only jacked in and connected to a clj repl via lein, and I couldn't reproduce the issue with that and the current Calva code.

I still made a change to use clojure-lsp for this though, but rather than spend more time trying to replicate your situation I figured I'd see if you had time to test it.
