### ISSUE TITLE
Jack-In Dependency Versions Based on deps.edn

### ISSUE THREAD

**Issue by brettrowberry** [BetterThanTomorrow/calva#1154]
The versions of nrepl and cider-nrepl used by Calva Jack in are listed in the Jack-In Dependency Versions section of https://calva.io/customizing/.

How can I have Calva use the versions defined in my deps.edn? I would like my config to be my defined solely by my project.

**Comment by bpringe** [comment]
I was wondering if the project versions would override the jack-in injections, but it seems maybe not.

> -Sdeps EDN     Deps data to use as the last deps file to be merged

@PEZ Is it necessary to start the repl then connect in order to have project versions of jack-in deps used?

**Comment by PEZ** [comment]
Hello!

Jack-in is something to use instead of having the dependencies in the project dependencies or user level deps. The idea here is that Calva's dependencies are not something that the project should need to care about.

So, no there is no way to do this. If the project ”wants” to handle this, then use the Connect command instead.

**Comment by brettrowberry** [comment]
That makes sense. I'll use Connect. Thanks!
