### ISSUE TITLE
Colorized ANSI output does not display as colorized in REPL window

### ISSUE THREAD

**Issue by alexandergunnarson** [BetterThanTomorrow/calva#1155]
How does Calva handle colorized ANSI output? I'm not seeing colorization on my end other than syntax highlighting. This may just be a limitation of VSCode / the way it does syntax highlighting; feel free to close this if so — I mainly wanted this for posterity in case other people encounter the same confusion as me.

Right now I'm keeping Calva's REPL open for individual expression evaluation, and using a terminal for full-file evaluation of a test file where I'm interested in seeing some colorized diffs, but it's not what I'd call a particularly convenient setup. Atom's `proto-repl` handled colorized output, but that's because it wasn't just a file; it was a webview of some sort or other. (Maybe this is what some old version of Calva did too?)

I assume there are good reasons as to why Calva started using a file, which benefits I just don't take much advantage of yet — maybe it's more familiar to newcomers, or provides more of a seamless experience in terms of paredit et al. So I'm not necessarily advocating a return to a webview, which seems an unlikely direction, but maybe there can be some fancy way of handling the colorized output in a file context; not sure.

Seems like these are functionally related issues, but they also seem implementationally irrelevant because of the webview → file progression Calva seems to have taken:
- https://github.com/BetterThanTomorrow/calva/issues/29
- https://github.com/BetterThanTomorrow/calva/issues/217

As always, thanks for your work on Calva — it's overall the best Clojure editing tool I've had the pleasure of using!

**Comment by bpringe** [comment]
Thanks a lot for the kind words!

>  provides more of a seamless experience in terms of paredit et al.

This is one of the reasons we switched, and I think was a pretty big one. See [this ClojureVerse post](https://clojureverse.org/t/calva-summer-of-bugs-2020/6303) for more info on that.

@PEZ Can probably tell you more about colorization.

**Comment by alexandergunnarson** [comment]
You're very welcome! :)

That makes sense about the switch. Thanks for the context! I'll sit tight for @PEZ to weigh in then — thanks!

**Comment by PEZ** [comment]
The old REPL window supported ANSI output, so that was one of the features we lost in that shift.

Calva has two types of syntax colorization:

1. tmLanguage grammar. The vscode built-in system for syntax highlighting. An extension can provide grammar -> VS Code will style the text. There is no API for the extension to do anything based on vscodes tokenization.
2. Calva Highlight. We parse the text according to a seperate grammar system and then add decorations (CSS) to the text.

System 2 is where rainbow brackets and rainbow guides happen. As well as matched bracket and unmatched bracket (and comment styling, and maybe more). It is also the same parser data/object that is helping Paredit and a lot of other features where Calva needs to know about the structure of the text.

None of these systems can be used for ansi colorization, as it would take adding those codes to the text document and that would have super weird side effects.

What we do today is try to strip the output from REPL evaluations from ansi codes so that they don't add clutter.

It might be possible to have a system where we have some parallell structure informing about what some ansi codes we have read would apply and then apply them, possibly part of colorization 2 step above. But I think that would be a quite huge undertaking inviting all too interesting bugs to happen.

We are considering adding some options about where to print stdout/stderr things, and depending on which options we would make available then, we could support ansi codes there.

**Comment by alexandergunnarson** [comment]
Thanks for the explanation @PEZ! Makes sense — that was pretty much what I was expecting and also what I was envisioning as to implementing this enhancement ("some parallel structure informing about ..."). Appreciate you weighing in!

**Comment by sohang3112** [comment]
@alexandergunnarson @bpringe Hi, I'm facing the same issue (ANSI color codes not working in Calva's REPL) - is there any solution / workaround for this?

**Comment by PEZ** [comment]
Hi @sohang3112! These days we have an output destination option that goes to a terminal. And there the ANSI escapes are honored. See https://calva.io/output/ for how to configure to use this. It comes with pros and cons. There's a new output window in the works that hopefully will be able to marry more pros with fewer cons.

Good that this issue floated up. Reminds me that I would consider it closed by the introduction of the Output Terminal, so closing it hereby. 😄
