### ISSUE TITLE
Command Palette shows Mac keyboard shortcuts on Windows/Linux

### ISSUE THREAD

**Issue by nilskassube** [BetterThanTomorrow/calva#1161]
I use Calva 2.0.194 on Windows 10 as the remote frontend for a WSL 2 Ubuntu system. The command palette shows the Mac shortcuts for these items:

- Paredit: Forward Sexp
- Paredit: Backward Sexp

**Comment by bpringe** [comment]
I think this is because in the extension manifest, the Mac shortcut is listed first, and the UI just shows the first shortcut listed: https://github.com/BetterThanTomorrow/calva/blob/e4e20daeb746f6dd2cd76bcccf8f471554edb8a7/package.json#L1514

@PEZ I seem to remember this was discussed before. Is this a VS Code issue that has been reported? I did a quick search in the vscode repo and didn't see anything related.

**Comment by ieugen** [comment]
This also affects Linux (Debian / Gnome ).

**Comment by bpringe** [comment]
I filed an issue upstream: https://github.com/microsoft/vscode/issues/126306

**Comment by bpringe** [comment]
A different method of assigning bindings per OS is mentioned here: https://github.com/microsoft/vscode/issues/126306#issuecomment-867222871, 

This might work for us, though I'd like to see if the original issue is resolved before using that method.

**Comment by PEZ** [comment]
It won't help. The problem is not that the OS is not reflected. It is. The problem is that we want to offer several binding options per OS, which is a part of the when context that the command palette is not designed to reflect.

But all is not lost. It seems VS Code insists on doing this thing consistently wrong. So by placing our default binding last in `package.json` that binding will be displayed. And then only be wrong when people change the `calva.paredit.hijackVSCodeDefaults` setting. At which point it does not do as much harm.
