### ISSUE TITLE
Custom repl commands are not evaluated in specified ns if different than current ns

### ISSUE THREAD

**Issue by zmitchell** [BetterThanTomorrow/calva#1196]
# Context
I'm working on a generative art project with Quil (Clojure bindings to Processing) that involves two namespaces. The first namespace `sketch.core` really just defines the sketch:

```clojure
(ns sketch.core
  (:require [quil.core :as q]
            [sketch.dynamic :as dynamic]))

(q/defsketch the-sketch
  :title "Sketch"
  :size [dynamic/d dynamic/d]
  :setup dynamic/setup
  :draw dynamic/draw
  :settings #(do
               (q/smooth)
               (q/pixel-density 2)))

(defn refresh []
  (use :reload 'sketch.dynamic)
  (.loop the-sketch))
```

The second namespace `sketch.dynamic` contains all of the code for making the drawing. As such, I make edits to the code and use the `refresh` function to re-draw everything. When I'm using Cursive the REPL is started in the `user` namespace, so I issue `(use 'sketch.core)` and then I can call `(refresh)` from the REPL when I want to re-draw.

# Problem
Calling `(refresh)` is something I do very frequently, so it would be convenient to assign a keyboard shortcut to that command. I've created the following custom REPL command:
```json
{
    "name": "Refresh sketch",
    "key": "r",
    "repl": "clj",
    "ns": "sketch.core",
    "snippet": "(refresh)"
}
```
I make some change in the `sketch.dynamic` namespace, send a form to the REPL, then execute the keyboard shortcut `ctrl+alt+space r` and I see this in the REPL output window:
```
clj꞉sketch.dynamic꞉> 
(refresh)
nil
```
No change in the drawing. I'm pretty new to Clojure, Quil, Processing, and Calva, so I'm not sure where in the stack the error is coming from. Can someone help me debug this?

**Comment by bpringe** [comment]
Hmm, I'll have to try this out later when I have time, if someone else doesn't get to it first.

**Comment by bpringe** [comment]
Does calling `refresh` without using a custom repl command work?

**Comment by zmitchell** [comment]
Yes, calling `(refresh)` in the output window does work. What's weird is that the output in the REPL window looks the same as when I execute the custom REPL command:
```
clj꞉sketch.dynamic꞉> 
(refresh) ; entered manually
nil
```

**Comment by bpringe** [comment]
If you can provide full reproduction code so we can try it, that would help (like what's in sketch.dynamic or some other code that you can reproduce this issue with).

**Comment by zmitchell** [comment]
This is `core.clj`:
```clojure
(ns sketch.core
  (:require [quil.core :as q]
            [sketch.dynamic :as dynamic]))

(q/defsketch the-sketch
  :title "Sketch"
  :size [dynamic/d dynamic/d]
  :setup dynamic/setup
  :draw dynamic/draw
  :settings #(do
               (q/smooth)
               (q/pixel-density 2)))

(defn refresh []
  (use :reload 'sketch.dynamic)
  (.loop the-sketch))
```
and this is `dynamic.clj`:
```clojure
(ns sketch.dynamic
  (:require
   [quil.core :as q ]))

(def d 500)
(def n 5)
(def cell-size (/ d n))
(def initial-rect-angle (- (/ q/PI 4)))

(defn size
  ([] (size 1.0))
  ([x] (* x d)))

(defn render-rect
  [{:rect/keys [angle x y width height]}]
  (q/with-translation [x y]
   (q/with-rotation [angle]
    (q/rect 0 0 width height))))

(defn grid-cell
  [row column]
  {:cell/width cell-size
   :cell/height cell-size
   :cell/x (* cell-size (+ column 0.5))
   :cell/y (* cell-size (+ row 0.5))
   :cell/row row
   :cell/column column})

(defn rect-angle
  [row column]
  (let [seq-number (+ column (* row n))]
    ; initial + ()
    (+ initial-rect-angle
       (rand (/ q/PI 4))
       (* (/ seq-number (* n n))
          (/ q/PI 4)))))

(defn cell->rect
  [{:cell/keys [row column x y]}]
  (let [angle (rect-angle row column)
        width (/ cell-size 2.1)
        height (/ cell-size 10)]
    {:rect/angle angle
     :rect/x (+ x (* (/ width 2) (q/cos angle)))
     :rect/y (+ y (* (/ width 2) (q/sin angle)))
     :rect/width width
     :rect/height height}))

(defn ellipse-noise-factor
  [row column]
  (/ (* 5 row column) 100))

(defn num-ellipses
  [row column]
  (+ 1 (* 6 row column)))

(defn ellipse-opacity
  [row column]
  (/ 4 (num-ellipses row column)))

(defn noisey-ellipse
  [{:cell/keys [row column x y width height]}]
  (let [divs 25
        wrad (/ width 2)
        hrad (/ height 2)
        noise-factor (ellipse-noise-factor row column)
        rad-coeff-center 0.8
        rad-coeff-min (- rad-coeff-center noise-factor)
        rad-coeff-max (+ rad-coeff-center noise-factor)]
    {:ellipse/x x
     :ellipse/y y
     :ellipse/vertices
     (map
      (fn
        [div]
        (let [angle (* q/TWO-PI (/ div divs))
              x-rad (q/random (* rad-coeff-min wrad) (* rad-coeff-max wrad))
              y-rad (q/random (* rad-coeff-min hrad) (* rad-coeff-max hrad))]
          [(* x-rad (q/cos angle))
           (* y-rad (q/sin angle))]))
      (range divs))}))

(defn render-noisey-ellipse
  [{:ellipse/keys [x y vertices]}]
  (let [padded-vertices (cons (last vertices) (concat vertices [(first vertices)]))]
    (q/with-translation
      [x y]
     (q/begin-shape)
     (doseq [[x y] padded-vertices]
       (q/curve-vertex x y))
     (q/end-shape :close))))

(defn setup []
  (q/color-mode :hsb 360 100 100 1.0))

(defn draw []
  (q/no-loop)
  (q/background 360 0 100)
  (q/rect-mode :center)
  (doseq [cell (for [i (range n) j (range n)] (grid-cell i j))]
    (q/no-fill)
    (if (= 0 (+ (:cell/row cell) (:cell/column cell)))
      ;; Draw a circle at the top left
      (do
        (q/stroke 360 100 0 1)
        (q/ellipse (:cell/x cell) (:cell/y cell) (* 0.8 (:cell/width cell)) (* 0.8 (:cell/height cell))))
      ;; Draw noisey ellipses at other grid locations
      (let [row (:cell/row cell)
            column (:cell/column cell)
            iter (num-ellipses row column)
            opacity (ellipse-opacity row column)]
        (q/stroke 360 100 0 opacity)
        (q/curve-tightness 0)
        (doall
         (repeatedly
          iter
          #(->> cell
                (noisey-ellipse)
                (render-noisey-ellipse))))))
    (q/fill 360 0 100)
    (q/stroke 360 100 0 1.0)
    (->> cell
         (cell->rect)
         (render-rect)))
  (q/save "sketch.png"))
```

**Comment by bpringe** [comment]
Ok, so I've found what seems like a bug in the custom repl commands, but also a method that should work for you.

## The problem

It seems when an `ns` is added to a custom repl command, the repl is not actually switching to that ns before running the snippet. With the following snippet (from above), if I'm in the sketch.dynamic namespace, then run the custom snippet to refresh, I get an error, `Unable to resolve symbol: refresh in this context`, and while the repl window looks like it's in the sketch.core namespace, if I run `*ns*` it shows sketch.dynamic as the namespace, then the prompt changes back to that.

```json
{
    "name": "Refresh sketch",
    "key": "r",
    "repl": "clj",
    "ns": "sketch.core",
    "snippet": "(refresh)"
}
```

I'm not sure if it's supposed to switch to the snippet namespace and then back, but either way it seems to not be running the snippet in the `ns` specified. CC @PEZ. Below is a gif showing the issue.

![custom-repl-command-bug](https://user-images.githubusercontent.com/12722744/122099176-90b60a00-cdc6-11eb-9fa6-f6e920761aa2.gif)

## A solution / workaround

You can remove the `ns` from your snippet definition and make the snippet `"(sketch.core/refresh)"`. This way the command will work no matter what namespace you're in since it uses a qualified symbol.

**Comment by bpringe** [comment]
Some notes from debugging:

We set the output window session here with a new ns: https://github.com/BetterThanTomorrow/calva/blob/35f1490fe0a8e43b3c19ecab37a83edf2a1973d3/src/evaluate.ts#L376

But, that doesn't actually change the repl ns (it just sets a property), as can be seen here: https://github.com/BetterThanTomorrow/calva/blob/35f1490fe0a8e43b3c19ecab37a83edf2a1973d3/src/results-output/results-doc.ts#L92

Then, it seems we assume that the output window ns _is the same as_ the actual current repl ns, though that's not true in this case. So in `evaluateCode` we check if the output window ns is the same as the ns passed in, and if it is we don't run `in-ns`. This line is skipped: https://github.com/BetterThanTomorrow/calva/blob/35f1490fe0a8e43b3c19ecab37a83edf2a1973d3/src/evaluate.ts#L62

So at this point, in my repro mentioned in the above comment, the current repl namespace is still `sketch.dynamic`, so then `(refresh)` is evaluated inside `sketch.dynamic` resulting in an error since `refresh` is not defined in that ns.

**Comment by bpringe** [comment]
@PEZ, I see in places where we're actually setting a new ns, there's usually a call to `in-ns` prior to the `outputWindow.setSession` call. I think we're missing a call to `in-ns` here: https://github.com/BetterThanTomorrow/calva/blob/35f1490fe0a8e43b3c19ecab37a83edf2a1973d3/src/evaluate.ts#L376

I think that would fix the above issue, and that maybe there's been an assumption that if a new `ns` was passed into that function, that the repl ns would be changed there. We probably just haven't seen many, if any, situations where this is a problem until now. Thoughts?

**Comment by bpringe** [comment]
@zmitchell I don't know exactly what was going wrong originally for you, but it seems it could have been related to the problem I discussed above. Please try this vsix and tell me if the custom repl command works for you: https://13787-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.201-fix-1196-custom-repl-command-eval-324aa4d1.vsix

If it downloads as a .zip, you need to change the extension to .vsix. Then in VS Code go to the Extensions side pane, then click the ellipses and click "Install from VSIX..." and choose the vsix file you downloaded. Reload the window and test it out.

**Comment by bpringe** [comment]
@zmitchell For the record, the drawing updated for me whenever `(refresh)` ran successfully. I changed `d` in `sketch.dynamic` to `1000` instead of `500`, then called `refresh` and it updated the sketch accordingly. Make sure you save the file before you call `refresh`.

Edit: I'm not sure if the issue I discussed above was really something you were having trouble with, but it was something I noticed is buggy when I was trying this example out.

**Comment by zmitchell** [comment]
I believe these are the same issue I was having, and I probably wasn't very clear on the real issue as a result of dirty REPL state. When I filed the issue I was seeing this when executing the custom REPL command
```
clj꞉sketch.dynamic꞉> 
(refresh)
nil
```
but now when I try it I see the same error you mentioned above.

The fix included in the .vsix works! Thanks for your help!
