### ISSUE TITLE
clojure-lsp statusbar message position

### ISSUE THREAD

**Issue by Hamido-san** [BetterThanTomorrow/calva#1205]
is there a way to show the clojure-lsp statusbar message to the **right** of the statusbar items?
vague question, I know, lemme explain:

instead of having the
`nREPL ⚡` `disconnected`
statusbar items suddenly shift to the right to make way for the clojure-lsp message resulting in
`🔄 Initializing Clojure language features...` `nREPL ⚡` `disconnected`
and a few seconds later suddenly shifting back to
`nREPL ⚡` `disconnected`

is it possible to just show the clojure-lsp message on the right, like this?
`nREPL ⚡` `disconnected` `🔄 Initializing Clojure language features...`
with the clear advantage being that the `nREPL ⚡` button wouldn't move around
(hopefully we all know how annoying a "moving" button is, right?)

**Comment by bpringe** [comment]
I think we can achieve this by using `createStatusBarItem` and setting a low priority (maybe 0?) rather than using `setStatusBarMessage`. `createStatusBarItem` returns a StatusBarItem, which I think we then use to set the text and show it. https://code.visualstudio.com/api/references/vscode-api#StatusBarItem

Actually, made we should implement that in statusbar.ts, where most other Calva status bar items are managed.

**Comment by bpringe** [comment]
We call `setStatusBarMessage` here and in another place in that file: https://github.com/BetterThanTomorrow/calva/blob/35f1490fe0a8e43b3c19ecab37a83edf2a1973d3/src/lsp/main.ts#L275

If we want to use `StatusBarItem` I think we'll need to manage the disposal ourselves once clojure-lsp has started.
