### ISSUE TITLE
Default to using the latest release of clojure-lsp

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#1248]
We should set things up such that Calva defaults to using the latest clojure-lsp release, rather than releasing new versions of Calva when clojure-lsp updates.

**Comment by bpringe** [comment]
I've thought about this before, but my concern was that if any changes in clojure-lsp require a change in how Calva uses it for something to work correctly in Calva, then things can be broken by default, and will be (by default) until we act to fix it. I think it's similar to why we wouldn't want to auto-update libraries our code depends on (at least not major versions).

Hopefully this wouldn't happen often, though, especially since clojure-lsp has matured a lot, but I guess we'll try it out and see. :smile:

**Comment by bpringe** [comment]
There's also the option of letting the user opt-in to using the latest version always, so they accept anything that might break, rather than making it the default. :man_shrugging:
