### ISSUE TITLE
Trailing whitespace not being stripped

### ISSUE THREAD

**Issue by ivanovishado** [BetterThanTomorrow/calva#1258]
Probably related to #364, but I had some whitespaces in this code:

```clojure
...
(defn arrived-at
  [hospital department person]

  (if (fits-in-queue? hospital department)
    (update hospital department conj person)
    (throw (ex-info "The queue is full" {:trying-to-add person})))))

...
```

At the end of the `if` line and had the `files.trimTrailingWhitespace` enabled, but it didn't remove the whitespaces when saving.

**Comment by bpringe** [comment]
Are you formatting on save (with formatting on save enabled), or are you formatting with the tab key?

**Comment by bpringe** [comment]
I notice it trims the white space for me when I hit `tab` on or near that line. Also, with the following settings, the white space is removed when I save the file:

```json
    "files.trimTrailingWhitespace": true,
    "editor.formatOnSave": true,
```

**Comment by zeitstein** [comment]
@bpringe that's right, but it doesn't trim with:
```json
"files.trimTrailingWhitespace": true,
"editor.formatOnSave": false,
```

**Comment by bpringe** [comment]
@zeitstein I tried with those settings and can reproduce.

@PEZ Any idea what Calva might be doing to prevent the trailing whitespace from being removed? I noticed with Calva disabled trailing whitespace is removed in clj and cljs files.

**Comment by zeitstein** [comment]
Any movement on this? My code keeps producing diffs like these when collaborating with non-Calva users.
![image](https://github.com/BetterThanTomorrow/calva/assets/8146007/4f46afd0-5a9a-4d2a-b8f2-4027b1957131)

**Comment by bpringe** [comment]
@zeitstein No movement that I know of, but in your image is that whitespace being removed? That would be the opposite (or expected outcome) of this issue, I think.

**Comment by PEZ** [comment]
> @PEZ Any idea what Calva might be doing to prevent the trailing whitespace from being removed? I noticed with Calva disabled trailing whitespace is removed in clj and cljs files.

I think that when Calva is registered as the formatter, VS Code does not do whatever it otherwise does for trimming whitespace. And Calva doesn't have a way to remove whitespace, while leaving the rest of the file alone. Currently, `formatOnSave` is the closest you can get to achieve this, as long as your cljfmt settings configure the removal of trailing whitespace.

@zeitstein, you are super welcome to have a look at this. I think there are several layers to it. The main problem I think is that when Calva isn't configured (by the user) to be the Clojure formatter, it still prevents the trimming. So if there is a way to stop Calva from registering itself as a formatter, that would at least give the user that option.

**Comment by zeitstein** [comment]
It seems to work when enabling the option explicitly for the language:
```json
"[clojure]": {
    "files.trimTrailingWhitespace": true
}
```

**Comment by PEZ** [comment]
Indeed, @zeitstein. Maybe the fix for this is to remove:

```json
    "files.trimTrailingWhitespace": false
```

From Calva defaults...
