### ISSUE TITLE
nbb nrepl-server: can only eval from file with extension .clj

### ISSUE THREAD

**Issue by borkdude** [BetterThanTomorrow/calva#1308]
Repro:

```
npm install -g nbb
nbb nrepl-server :port 1337
```

Connect from Calva, generic REPL session to `localhost:1337`

Then eval some expressions like below from `.cljs` file:

``` clojure
(defn version []
  js/process.version)

(version)

(require '["fs" :as fs])

(fs/existsSync "README.md")
(fs/existsSync "README2.md")

(require '[clojure.string :as str])

(first (str/split js/process.env.PATH ":"))
``` 

This doesn't work, but it does work when renaming the file to a `.clj` file.

**Comment by PEZ** [comment]
A ClojureScript nREPL server? Now that changes things!

We have several reasons to visit Calva's session management, and here we get yet another one.

As a hacky workaround the user can add this Custom REPL Connect sequence settings:

```json
  "calva.replConnectSequences": [
    {
      "projectType": "generic",
      "name": "nbb Connect Workaround",
      "cljsType": {
        "dependsOn": "User provided",
        "connectCode": ":fake-it",
        "isConnectedRegExp": ":fake-it"
      }
    }
  ]
```

It works because Calva assumes it connects to a Clojure REPL, but doesn't actually care, as long as it speaks nREPL. For ClojureScript it then clones the first session and promotes it to a ClojureScript one using whatever facilities provided in the Clojure session. With nbb nREPL there are no such facilities, of course, and none are needed.

The workaround creates a pretty weird Ux with Calva indicating that it has a Clojure REPL which is really a ClojureScript one, but anyway.

**Comment by PEZ** [comment]
As for the Ux. As long as you work with ClojureScript files, it will be quite fine. 😄

**Comment by borkdude** [comment]
@PEZ Awesome: that works!
