### ISSUE TITLE
Run All Tests command doesn't run tests in .cljc file with reader conditional in ns

### ISSUE THREAD

**Issue by andriikovalov** [BetterThanTomorrow/calva#1328]
Steps to reproduce:

1. Create a new lein app `lein new app test-app`
2. Rename `core_test.clj` in to `core_test.cljc`
3. In `core_test.cljc` change `[clojure.test :refer :all]` to `#?(:clj [clojure.test :refer :all])`
4. Open project directory in VS Code, jack-in
5. Invoke Run All Tests command, expected: failing test in REPL, actual: "No tests found"

**Comment by bpringe** [comment]
Do any of the other test commands work in this situation? I wonder if cider-nrepl (which is used for running tests), only checks `.clj` files.

**Comment by andriikovalov** [comment]
Yes, I tried "Run tests for current namespace" and "Run current test", and they both work (I see output with test results in REPL).

Here are some other things I noticed with "Run all tests":

- `.cljc` file without reader conditionals: works
- `.cljc` with a reader conditional inside a test: works
- `.cljc` with a reader conditional in `ns :require` (as in the description): no tests found

**Comment by bpringe** [comment]
Interesting, thanks for the added details.

**Comment by bpringe** [comment]
So, Calva is running the deprecated `test-all` op of cider-nrepl to run all tests.

We can try using the not deprecated `test-var-query` op to run all tests and see if that fixes this issue. I noticed that running the tests for the namespace works, which uses `test-var-query`.

@marcomorain Since you've been working on test-related stuff, would you like to tackle this when you have time? If not, I can do it eventually.

**Comment by marcomorain** [comment]
I'm taking a quick look now.

**Comment by marcomorain** [comment]
👍 PR open which fixes this.
