### ISSUE TITLE
ctrl+k for Kill Right conflicts with several bindings on Windows

### ISSUE THREAD

**Issue by yunerbekir** [BetterThanTomorrow/calva#1356]
The **Kill Right** (ctrl+k or cmd+k) command overwrites the **single line comment chord** on Windows (ctrl+k ctrl+c)

**Comment by PEZ** [comment]
Almost all `cmd+k` chord on Mac are `ctrl+k` chords on Windows.

A workaround for now could be to use the **Toggle Line Comment** command. `cmd+/` on Mac, so maybe `ctrl+/` on Windows?

**Comment by yunerbekir** [comment]
That is a workaround, many users are used to the `ctrl+k ctrl+c` combination. If memory serves me right that is the same combination from Visual Studio

**Comment by xfthhxk** [comment]
from Slack discussion:

amar: so ctrl+alt+k is free. ctrl+shift+alt+k is used for Calva Paredit: Drag Sexp Forward Up. so not sure how we can keep a similar mnemonic
pez: I wonder if ctrl+e is bound to something interesting on Windows…

@yunerbekir is right `ctrl+k ctrl+c` is a basic [key binding](https://code.visualstudio.com/docs/getstarted/keybindings) 

What about `ctrl+alt+k r` for kill right and `ctrl+alt+s r` for select right?

**Comment by PEZ** [comment]
Is `ctrl+k ctrl+k` free?

**Comment by PEZ** [comment]
Now checked. Not listed here: https://code.visualstudio.com/shortcuts/keyboard-shortcuts-windows.pdf

In VS Code for Mac I see:

```json
{
  "key": "cmd+k cmd+k",
  "command": "editor.action.selectFromAnchorToCursor",
  "when": "editorTextFocus && selectionAnchorSet"
}
```

A guess is that it is `ctrl+k ctrl+k` on WIndows. Which would mean we can use it. We can have `!selectionAnchorSet` in the `when` clause and there wouldn't even be a conflict.

**Select Right** would need to be `ctrl+k ctrl+shift+k`, because `ctrl+shift+k` is taken by VS Code, but that'll have to do, I think.

**Comment by xfthhxk** [comment]
[This]( https://code.visualstudio.com/docs/getstarted/keybindings) seems to have `ctrl+k ctlr+k` tied to launching the key bindings editor? Confusing which source to believe. I like the `ctrl+k ctrl+k` for windows... more ergonomic.  @PEZ I'll take a shot at the key chords you suggested.
