### ISSUE TITLE
Copilot + Calva integration

### ISSUE THREAD

**Issue by dmrd** [BetterThanTomorrow/calva#1461]
Copilot does a great job of predicting clojure(script) code. Unfortunately TAB completing its suggestions does not work when Calva is enabled. 

Mirror of issue from copilot repo: https://github.com/github/feedback/discussions/7413

**Comment by bpringe** [comment]
I left a comment on that linked discussion which is pasted below.

> Calva maps tab to its command for formatting the current form. As a workaround, you can map that command to some other key in the keyboard shortcuts or simply remove the mapping (formatting with a keyboard shortcut is pretty handy though 😄 ).

I believe I did something similar to the above with Copilot in the past, but it's been a while since I used it just due to a reinstallation of VS Code or switching to a new computer and not reinstalling Copilot. I should reinstall it...

**Comment by PEZ** [comment]
I think I have fixed this. Please re-open if that is not true.
