### ISSUE TITLE
Visual Studio Code - Light bulb suggestions

### ISSUE THREAD

**Issue by isacjunior** [BetterThanTomorrow/calva#1499]
All the suggestion given by the light bulb doesn't work. On the other side, the commands that bring the same result work.

<img src="https://calva.io/images/refactoring/quick-fix.png" width="500">

```
VSCode: 1.63.2
Calva: v2.0.236
clojure-lsp version used: 2021.12.01-12.28.16
clj-kondo version used: 2021.10.20-SNAPSHOT

nREPL dependencies configured:
    nrepl: 0.9.0
    cider-nrepl: 0.27.4
    cider/piggieback: 0.5.3
  clojure-lsp path configured: /usr/local/bin/clojure-lsp
  ```

**Comment by bpringe** [comment]
Thanks for reporting. I cannot reproduce the issue. It seems you've configured clojure-lsp to run from a custom path:

> clojure-lsp path configured: /usr/local/bin/clojure-lsp

Can you try downloading the latest version of clojure-lsp and setting Calva to use it, or removing the configured path and reloading the window so that Calva uses the latest clojure-lsp? Let me know if that fixes the issue.

**Comment by isacjunior** [comment]
Using the `clojure-lsp` without a custom path works.

**Comment by bpringe** [comment]
Awesome. It was probably some issue with the version you were using at the custom path. Did you try to use the latest version with a custom path? Let me know if that works.

**Comment by isacjunior** [comment]
Works with custom path using the last version.
