### ISSUE TITLE
 'Show Previous REPL History Entry' command not working on v.2.0.237

### ISSUE THREAD

**Issue by LouDnl** [BetterThanTomorrow/calva#1504]
When in REPL window ALT + Up Arrow does not give you the previous command. It either does nothing or randomly throws a command from history at you.

Works just fine in v.2.0.235
https://clojurians.slack.com/archives/CBE668G4R/p1643273088767469

**Comment by bpringe** [comment]
This should be fixed in 2.0.237, thanks to @cyrik.

**Comment by TuggyNE** [comment]
Looks to me like it's still happening in 2.0.237. First time I use the shortcut it does nothing. Next time it jumps through two or more previous runs to pick up something else. It seems to be capable of recognizing very simple commands from the current session (e.g. literals) but successful fn calls are not included in history.

**Comment by Cyrik** [comment]
@TuggyNE do you have an example? And what is the flow that does not work for you?
If I write `(mapv inc (range 1000))` into the output.calva-repl file and hit enter it shows up in my history.

**Comment by TuggyNE** [comment]
@Cyrik Before I downgraded, pretty much any call was executing but being left out of <kbd>⌥</kbd>+<kbd>Enter</kbd> history. The simplest example I had tried was a math one-liner from core: `(-> 1 (* 2) (/ 3.0) (Math/round) long)`. A non-threaded, multi-line fn call with one of my own fns was also omitted. As mentioned, numeric literals made it into history. I wasn't sure what else to try in between those.

With another REPL that was still running with 2.0.237, I tried out the math one-liner above. It showed up in history this time, but `(mapv inc (range 1000))` did not, nor several other expressions, including a simple call of a no-arg custom fn: `(version)`. All I see is a single blank entry, then the previous successfully-included entries.

Another quirk is that on one or two occasions, something has shown up (most recently `()`) but then another evaluation (i.e. `'([])`) has not only not shown up, but wiped out the previous successful history inclusion. Some entries are not affected by this, though.

Nothing relevant shows up in the error console or any logs I can find. (There are a few errors in Extension Host output from Calva, but they are not correlated by time or number or message to the actual problems.)

**Comment by Cyrik** [comment]
@TuggyNE thank you for the detailed report! I can now actually reproduce it. It seems "eval top level" inside the repl breaks part of the history. I'll have a look at it tomorrow. Until then, just hitting "enter" works fine.

Off-topic question: is there a reason you are evaluating things inside the repl file? Until this bug I didn't even know there was a history because I'm never in that file.

**Comment by TuggyNE** [comment]
@Cyrik: OK, good to hear.

I use the REPL for free-form investigations and some proof-of-concept or initial testing that doesn't really need to go into long-term history. Anything in rich comments (as well as just form evaluation) in files is typically for more stable things, like debug expressions I use over and over again, or property tests.

I suppose I could keep a scratchpad that's not in VCS and doesn't go away when the REPL is restarted, but it's never really been worth the trouble. (In fact, in recent months the REPL has actually become a little nicer, since VS Code and Calva performance have improved even when it's full of thousands of lines of output.)

**Comment by bpringe** [comment]
Just reopening this until the fix is released.

**Comment by PEZ** [comment]
I'm confused. Is this fixed or not? 😄

**Comment by Cyrik** [comment]
@PEZ Fixed with #1514, unless more stuff comes up.
