### ISSUE TITLE
[2.0] jumping between source and repl should be streamlined

### ISSUE THREAD

**Issue by Gnurdle** [BetterThanTomorrow/calva#153]
having to go back and forth with the mouse is painful.
the cider buffer-switch ^X^O was also awkward, but a lot less disruptive than having to mouse.

Right now, getting to the command-line on repl is double-hard, because you also have to play a game of clicking where the cursor was to get "focus".

I'm not sure exactly what the aesthetics should be, but something that takes me to a hot/focused repl prompt from inside the editor would help, and perhaps on the way out, it could record exactly where I was so that the next press of that key took me right back where I was in the source.  perhaps a single binding to jump back and forth between them?

**Comment by PEZ** [comment]
I think the vscode built-ins are pretty good for switching bewteen the REPL and the code. Depending on how you have grouped and placed things, different commands help you.

* By default Calva will open the REPL window in a different group than the current edited file. To the right, I think, even. So then the easiest (imo) commands for switching between the edited file and the repl is the *Go->Switch Group->Group Left/Right/Up/Down*. On Mac they have easy to remember keyboard shortcuts.
* If you have the repl window in the same group as your edited file there are commands for switching between editors in the same group.

You mention the focus problems, which is relevant. Because if that was not there it would be more obvious that the commands for jumping between the previous and next locations work as well. I have filed the focus thing as an issue of its own: #161 .

**Comment by Gnurdle** [comment]
I think the advice of using the window switching key bindings is enough to warrant closing this one - it's good enough, and it makes sense

**Comment by PEZ** [comment]
We'll track this in #339 , would you agree?

**Comment by Gnurdle** [comment]
wfm
