### ISSUE TITLE
Showing unwanted "Problems" from outside the project

### ISSUE THREAD

**Issue by jacobemcken** [BetterThanTomorrow/calva#1553]
How to reproduce

Prepare by:
- Create an empty project (I used Leiningen)
- Add an external dependency with "problems" (I used `[clojure.java-time "0.3.3"]`)
- Jack-in to a REPL
- Add the following code (comment block):
```clojure
(comment
  (require '[java-time :as time])

  (time/instant)
  )
```

Two things seems to report unwanted external "Problems" in the bottom tab:
1. Navigate to external code (<kbd>Ctrl+&lt;mouse click&gt;</kdb>). E.g. by clicking on a `java-time`.
2. Have `java-time` required by the namespace. This can be done manually by evaluating the form `(require '[java-time :as time])`. Then hold <kdb>Ctrl</kdb> while hovering `time/instant`.

**Comment by PEZ** [comment]
I vaguely remember seeing something about clj-kondo linting dependencies. Might be something you can configure away. Pinging @borkdude and @ericdallo

**Comment by jacobemcken** [comment]
Regardless, being able to disable this behavior seems like a workaround.
IMO the best out-of-the-box experience with Calva would be "only reporting problems I can fix".
I don't want my own "problems" drowning (hiding) in outside "problems". I guess it is also psychological. Fixing 2 problems out of 20 is a 10% reduction. Fixing 2 problems out of 265 (which includes external problems) is like "bah, whatever - not going to make any significant difference".

Personally, I would rather not be able to see external problems at all, compared to seeing them involuntarily.

**Comment by PEZ** [comment]
Yes, I agree. Problems should not be reported on read-only libraries. There is not much Calva can do about it, I think. Configuring it away is a workaround, as I see it. And I am not even sure you can do that.

**Comment by ericdallo** [comment]
This was an issue on clojure-lsp already fixed which should be available on next release (couple of days)
From changelog:
> Don't return diagnostics for external files like files on jar dependencies, avoiding noise on lint when opening dependencies.

If you want to give it a try and feedback if your issue was solved, you can download a nightly build from [#clojure-lsp-builds](https://clojurians.slack.com/archives/C032YH7P0R2)

**Comment by jacobemcken** [comment]
I can confirm that the Linux binary you linked works - it doesn't scan external dependencies anymore.

**Comment by bpringe** [comment]
I sometimes close these at times like this so we don't forget to come back and do so when the fix in clojure-lsp is released. I'm still not sure it's a bad idea, as the issue is still searchable (but closed, so maybe someone would miss it). What are your thoughts on this @PEZ?

There should be a reminder feature on issues, like `/remind` of Slack... though I can also just use that 😄 .

**Comment by ericdallo** [comment]
I'm totally ok to keep it until the fix is released

**Comment by jacobemcken** [comment]
This has been fixed with the recent version of [clojure-lsp 2022.02.23-12.12.12](https://github.com/clojure-lsp/clojure-lsp/releases/tag/2022.02.23-12.12.12).

Specifically:
> Don't return diagnostics for external files like files on jar dependencies, avoiding noise on lint when opening dependencies.

**Comment by PEZ** [comment]
Thanks for updating, @jacobemcken !
