### ISSUE TITLE
Change Paredit navigation command labels to include the word "Navigate" or "Navigate Cursor"

### ISSUE THREAD

**Issue by riotrah** [BetterThanTomorrow/calva#1660]
# What:

Have the series of Paredit structural cursor navigation commands' labels start with `Calva Paredit: Navigate Sexp Forward Or Up` etc.

Many options exist, though I'm not sure if there exist conventions from the LISP universe that would be more nostalgia-inducing, open to those as well of course.

Some Options:

- Jump/Jump to
- Go to
- Propel
- Navigate
- Leap
- Shimmy
- etc

# Why:

When I want to see all the paredit navigation commands in the vsc keybindings viewer my only choice to search/filter is something like:

**Search term**: "paredit forward sexp"

**Results**: 
<img width="453" alt="image" src="https://user-images.githubusercontent.com/22646419/161401703-b1f2dc70-0f5f-49a9-8d69-bd2366828943.png">

**What I really wish I could do**: "paredit navigate/jump/move/etc forward sexp"

**Results I really wish I could get:**

- The results ƒrom the screenshots, but minus the:
  - barf, 
  - drag, 
  - kill/delete, 
  - select, 
  - slurp, and 
  - splice commands 

# Probably Work to Do:

- Extension manifest -> `contributes` -> `commands` changes
- Probably _lots_ of documentation changes lol

**Comment by PEZ** [comment]
Shimmmy! 😀

How about ”Move”? Or “Cursor”?

I like the idea here. Let's do this.

**Comment by PEZ** [comment]
Seems like in built in VS Code commands **Move** is similar to our **Drag**.

The debugger commands have **Go** to navigate between breakpoints and such. 

**Navigate** is used to move between views, e.g. **View: Navigate to View Above**

**Cursor** is used to add cursor and some more, e.g. **Add Cursor Above**

Those were all from the command palette. If we search in the keybinding editor, like you do in OP, @riotrah, we can find prior art with **Cursor** like so:

<img width="983" alt="image" src="https://user-images.githubusercontent.com/30010/161415217-446d4869-78f1-46fe-8b5e-4730456c949a.png">

I say that if we have a verb to go vid **Cursor**, that would work nicely with the built in **Cursor** commands. And then we can choose between **Move** or **Navigate** to harmonize well with those built-ins. I think I prefer **Move Cursor**, so:

**Calva Paredit: Move Cursor Forward Sexp/Form**

I've added **/Form** there because if we are going to change this we could as well do this change, which I've been wanting to do a while. All in the spirit of SEO.

**Comment by riotrah** [comment]
Sounds great - want me to take a stab at this then?
