### ISSUE TITLE
Syntax Highlighting of Docstrings

### ISSUE THREAD

**Issue by d4hines** [BetterThanTomorrow/calva#173]
Hello!

I'm giving Calva a try, and so far I'm really liking it! Great work! This is a big deal for wider Clojure adoption.

One thing I noticed right away is that docstrings are highlighted as normal strings.

In Spacemacs with the Clojure layer enabled, docstrings are highlighted some other distinctive color, to differentiate them. For `defn` especially, this is a big help towards preventing me from placing the string in the wrong spot 😝 

Screenshot:
<img width="573" alt="Screen Shot 2019-04-27 at 12 00 43 PM" src="https://user-images.githubusercontent.com/25231383/56852059-2ee36f00-68e4-11e9-84b6-de156f2d607b.png">

How hard would this be to implement? Happy to take a stab at it myself if you can point out where to start.

**Comment by PEZ** [comment]
Hi! Happy you like it! I share your sense for this being important for growing the Clojure user base. Calva has the potential to making the getting-started story really sweet. We're not quite there yet, but we work hard and are stubborn. :smile:

I'm not sure how hard it would be to do this. I think that the grammar is probably easy enough. (I could be wrong.) But there is also the fact that vscode doesn't provide an API for amending the themes. But if you find a symbol/token that is already there, and not used by the Clojure grammar, the latter problem is not there.

I've decided to let Calva override vscode's built in Clojure grammar (because the process of getting changes in there is super slooooooowwwwww). So at least we are in control over the grammar. Take a look in `calva/calva-fmt/atom-language-clojure`. There's a `spec`, making it quite speedy to iterate the grammar.

You know where to find me if you need some more intro. It was a while since I worked with it, but I still remember some of it.

**Comment by cfehse** [comment]
@d4hines 

This issue should be fixed in version 2.0.57. I am closing this issue for now.
