### ISSUE TITLE
Name change for loading/evaluating a whole file for better command lookup

### ISSUE THREAD

**Issue by alpox** [BetterThanTomorrow/calva#1731]
With respect to the often occurring question for the existence of a command to evaluate a whole file as also stated at: <https://ask.clojure.org/index.php/11892/calva-is-there-a-way-to-evaluate-a-whole-file> I suggest adding the word `Eval` to the command name.
This would make the command appear alongside all other commands that evaluate things. Currently, when looking for `eval` commands this particular command (Evaluating a whole file) won't show up which may confuse some users (Me included). I was not able to find the command for a while due to this.

Current name: **Calva: Load Current File and Dependencies.**
Suggested name: **Calva: Evaluate Current File and load Dependencies.**

**Comment by bpringe** [comment]
In case you weren't already familiar, the current name I think stems from the [load-file function](https://clojuredocs.org/clojure.core/load-file). Calva uses the [nrepl load-file op](https://nrepl.org/nrepl/ops.html#load-file) for the command. But in any case, I agree that adding "evaluate" to the command name will help avoid some confusion.

@PEZ What's do you think the new name should be for the command?

I'll offer other suggestions alongside @alpox's:

1. Calva: Load/Evaluate Current File and Dependencies
2. Calva: Load/Evaluate Current File

I'm not sure we need to mention "and Dependencies" as the description for the actual Clojure function and the nrepl op do not. Dependencies aren't really being "loaded" either, they're being evaluated. But still, it might also help avoid some other confusion.

I think it's important to keep "Load" in the command name, though, since some users familiar with Clojure and `load-file` may search for "load" when they're getting started with Calva.

**Comment by PEZ** [comment]
Thanks @alpox and @bpringe for this discussion and for the suggestions! *Load/Evaluate* is good in that it follows a pattern that we use for other similar SEO purposes, e.g. *Form/Sexpr* for many Paredit commands. I think I like **Calva: Load/Evaluate Current File and Dependencies** best. It will be a load of dependencies the first time, resulting from the evaluation, right? Maybe also add *Requires* there:

**Calva: Load/Evaluate Current File and its Requires/Dependencies**

?

**Comment by PEZ** [comment]
If you want your Calva *Contributor* badge, @alpox, this is a pretty nice little issue. It'll be the name change and some documentation updates. In my book you are already a contributor for pointing this issue out, but it's nice with a badge too. 😄

**Comment by alpox** [comment]
@PEZ Thanks for the opportunity to get a badge! 😄 I created a Pull-Request and hope I followed the guidelines alright and found all the relevant documentation to update!

**Comment by PEZ** [comment]
Right back at ya! Perfect PR.
