### ISSUE TITLE
Better integration with live share: push evaluation decorations

### ISSUE THREAD

**Issue by teves-castro** [BetterThanTomorrow/calva#182]
Currently when evaluating a form during a live share session the resulting decorations are not being shown on the other participants editors.
By using the [VS Live Share Extension API](https://www.npmjs.com/package/vsls) it might be possible to create a kind of a chat service amongst live share participants to push those evaluations to every other participant.

**Comment by niclasnilsson** [comment]
This is a very interesting thing. We're using Calva with Live Share right now, and to get pair programming to work that way, we have to share screen with Hangouts at the same in order to see the REPL output (we're using the output window more that the editor "decorations). 

The way we work is that we're pair-programming or mob-programming and collaboratively editing with Live Share, but the biggest problems are 1) not being able to see the REPL of the common session, and 2) Not being able to evaluate in the shared session (read: the REPL of the one who created the session.)

Is there any hope that this could work over Live Share, at least on the level of "Shared Terminals" to see the output, and even better if the eval could be done on the session initiators machine?

**Comment by PEZ** [comment]
Hi @niclasnilsson! For now what Calva can offer is a feature that @teves-castro added: **Evaluate current form and append as comment** (exact wording eludes me right now), the default shortcut is <kbd>ctrl+alt+c</kbd>, <kbd>c</kbd>.

Regardless of Live Share or not I recommend taking the advice from Stuart Halloway of getting into the habit of using the REPL inside the editor, instead of at the REPL prompt.  Calva has a special treatment of `(comment)` forms intended to assist with this. The **Evaluate top level form** treats the `(comment)` form as creating a new top level, so <kbd>ctrl+alt+c</kbd>, <kbd>space</kbd> does ”the right thing” there.

**Comment by PEZ** [comment]
Yes, about where the evaluation is done. I _think_ you can achieve that by the session initiator opening the REPL port over Live Share, and the participants connecting Calva to that port. Not sure about this though, it was a while since I Live Shared anything...

**Comment by niclasnilsson** [comment]
Agree fully. We never type anything in the REPL, just sending forms to it, but in our case, due to the data we're manipulating, it's often easier see the result in the REPL output. Pretty printing in different ways, print-table and stuff can come in pretty (pun intended) handy at times.

**Comment by niclasnilsson** [comment]
And thanks, I'll take another look and see if we can open the REPL port to Live Share.

**Comment by PEZ** [comment]
I just released Calva v2.0.40. It offers a hover for the evaluated form which displays the result. Pretty printed, if that was what you ordered when evaluating. I don' t know if this hover transfers well over Live Share, but I am curious, so please test it and let me know.

**Comment by bpringe** [comment]
@niclasnilsson A friend and I shared a REPL with live share by me (the initiator) sharing my repl port through live share, as @PEZ was saying. I don't remember the exact details, but he could define a function on his end, and I could use it on my end.

**Comment by PEZ** [comment]
How much of this is still relevant? Maybe @svdo knows?

**Comment by svdo** [comment]
I think it can probably be closed. If I encounter issues like this coming week (when I'll be testing live share support) I'll open new tickets.

**Comment by bpringe** [comment]
Closing this now. Let's reopen this or open separate issues if needed.

**Comment by bpringe** [comment]
@svdo Question: Are eval decorations shown in live share for all participants? If not, is there an easy way to broadcast the eval results besides using the "eval to comment" command?

**Comment by svdo** [comment]
I only know that the decorations only work locally. Personally that's the way I like it, but YMMV...
