### ISSUE TITLE
Cannot detect syntax errors 

### ISSUE THREAD

**Issue by pubnoconst** [BetterThanTomorrow/calva#1852]
I am not getting any syntax error flag in the following piece of code. Note that I am very new to clojure myself and unable to determine other ways to reproduce this.

```clj
(ns rps4.core
  (:gen-class))

(defn game-loop []
  (loop []
    (println "Rock Paper Scissors. Enter R/P/S or Q to quit")
    (let [guess (rand-nth ["R" "P" "S"]) answer (read-line)]
      (println "My guess is" guess)
      (cond
        (contains? {"R" "P" "S"} answer) (println "TODO") ;; Should be #{"R" "P" "S"}
        (= answer "Q") (println "Quitting")
        :else (println "Invalid input, try again"))
      (when-not (= answer "Q") (recur))
      )
    ))
(defn -main
  []
  (game-loop))
```

I am running Calva `v2.0.298` on VS Code `1.70.2`.

To reproduce, I ran `lein new app rps4` and replaced the contents of `core.clj` into the code above.

**Comment by PEZ** [comment]
Hello, I'm not sure what you mean by syntax error flag. If you evaluate this, it should fail giving you a syntax error that points at the error with the uneven forms map.

**Comment by pubnoconst** [comment]
> Hello, I'm not sure what you mean by syntax error flag.

Sorry for the bad English. I meant error squiggles under the erroneous AST in the editor field.

**Comment by PEZ** [comment]
There are no squiggles for that.

The place where this would be implemented is in the linter. With Calva this is [clj-kondo](https://github.com/clj-kondo/clj-kondo) (by proxy of clojure-lsp). So you can either define your own linter for this, using clj-kondo configuration, or have it default added to clj-kondo.

I'm closing this, because there is no action we can take on Calva. Please feel invited to keep discussing it.
