### ISSUE TITLE
Show accurate message when clojure-lsp fails to download

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#1896]
I noticed when the clojure-lsp nightly build download was failing. An error would be logged in the developer console but a popup info message would show that an older version was downloaded. We should show an error popup explaining that the download failed instead.

```text
[Extension Host] Error downloading clojure-lsp. Error: Not Found
```

Nightly was attempted to be downloaded, the download failed, and this message popped up.

![image](https://user-images.githubusercontent.com/12722744/195726417-0c8fb5db-c9bf-4e17-9e90-57f8e567ac11.png)

**Comment by bpringe** [comment]
Related issue (it could have been more obvious that the download failed): https://github.com/BetterThanTomorrow/calva/issues/1713

We should put the URL in the popup message when the download fails.

**Comment by Hamido-san** [comment]
Not sure if related, but I've also noticed clojure-lsp fails to download when using vpn

0. cloudflare warp is on
1. open project > "failed to download clojure-lsp"
2. turn cloudflare warp off
3. click "clojure-lsp" button is status bar > download latest version
4. "downloading..." > "downloaded to..."
5. turn cloudflare warp back on
6. everything else works

**Comment by PEZ** [comment]
@bpringe , I vaguely remember doing something around this. Can you check if the issue is still valid, or if it needs to be restated, or whatever. =)

@Hamido-san It does not seem related. I don't know if it is supposed to work with CCloudflare warp. That would depend on what that VPN is doing. But if you think it should work, you are welcome to file a new issue. Unless you are already aware, there's an option for referencing  your comment in a new issue via the meatballs menu on the comment:

<img width="296" alt="image" src="https://github.com/BetterThanTomorrow/calva/assets/30010/acff19a1-f577-489d-b270-75ac748b862b">

**Comment by bpringe** [comment]
I don't know if this is the exact repro, but I set the clojure-lsp version to nightly, turned off my machine's wi-fi, then reloaded the window, and saw this popup:

![image](https://github.com/BetterThanTomorrow/calva/assets/12722744/a1f7a465-6a81-47b4-bb3d-d0741454cd93)

So I'll call this fixed. 🎉
