### ISSUE TITLE
Option to disable focussing Calva says on eval

### ISSUE THREAD

**Issue by felixlinker** [BetterThanTomorrow/calva#191]
I have the option `calva.evalOnSave` enabled but what annoys me is that on every file save, the focus is put on the "calva says"-output whereas I'm more interested in linter annotations to my code. This disrupts my workflow as I'd prefer to have the terminal left open.

I thought this might be easy to implement and started an development environment for this extension but wasn't able to reproduce this behavior with the dev version. My question now is: Has this actually changed or is it just some twist to the development environment?

If this already is implemented on `dev` I'm happy for this issue simply to be closed.

**Comment by PEZ** [comment]
It makes me happy that you set out to fix this! Generally, there are no twists in the dev environment, it behaves very much like the release builds. (FYI)

I do not recall fixing this but git blame says that @mrkam2 might have. In any case, it is explicitly made so that focus is not changed, here:

https://github.com/BetterThanTomorrow/calva/blob/dev/calva/evaluate.ts#L139

Please consider checking the issues list and see if there is some other issue you can fix. :smile:

**Comment by felixlinker** [comment]
Thanks for the response. So just to be clear, I wasn't sure whether I got step three of [The-Setup](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute#the-setup) correctly: You are meant to open a `.clj` file in the same VS Code instance your are editing the plugin with, right? So I'm not supposed to use the editor that launches when I hit `F5` at all or should I be using that instance?

**Comment by PEZ** [comment]
To test the extension you are developing on you use the vscode window that opens when you hit `F5`.
