### ISSUE TITLE
"see also" links in function popup window do not work

### ISSUE THREAD

**Issue by jamiepratt** [BetterThanTomorrow/calva#1972]
<img width="259" alt="Screenshot 2022-11-21 at 10 27 34" src="https://user-images.githubusercontent.com/558780/203067941-039701e7-4417-422e-b030-c5f4a2f49c9c.png">

I'm not sure if this is an issue with calva but @PEZ asked me to report it. In some projects the "see also" links at the bottom of the function popup window below the code examples do not functions as clickable links although they appear to be hyperlinks. In some projects they are clickable.

[Here is a project](https://github.com/hanshuebner/clj-oauth2-token-generator) where the links aren't clickable for me.

**Comment by jamiepratt** [comment]
<img width="580" alt="Screenshot 2022-11-21 at 13 38 31" src="https://user-images.githubusercontent.com/558780/203069449-cd11e624-3527-445d-987e-8658536f8be5.png">

|Here is an example of another project where in the popup for defn, the links are clickable:

https://github.com/heroku/clojure-getting-started.git

**Comment by jamiepratt** [comment]
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:22:48.959Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

**Comment by PEZ** [comment]
Thanks for reporting! I don't think this is about the project, but rather about wether you connect the REPL or not. Because when you connect the REPL, Calva renders the Clojuredocs examples, while when there is not REPL, this is done by clojure-lsp, which creates links for the see also items.

**Comment by jamiepratt** [comment]
Ah! Yes it whether I am jacked in that makes the difference.

**Comment by PEZ** [comment]
This should be fixed in the VSIX for this PR:

* #1970 

(Because I was making some changes to the Clojure docs pop-up stuff when you reported the issue, so it made sense to me to just fix this as well, while I was up-to-date with the code.)

It would be super great if you want to test it, there is a lot that could go wrong in that PR. Assuming you don't know how to find the VSIX:

1. At the bottom of the PR page, you'll find a message **All Checks have passed** (hopefully, lol). 
    <img width="963" alt="image" src="https://user-images.githubusercontent.com/30010/203082715-ee8d56e4-4a88-40b7-893c-7a7dc178864c.png"> 
3. Click **Show all checks**
4. Click **Details** on the `build` task/check.
5. Click the **ARTIFACTS** tab
6. You should see the download link. Download it. 😄 
7. In the VS Code Extensions tab, use the top meatballs menu to **Install from VSIX...**
 
Sometimes the file downloads with a `.zip` file extension. If this happens, rename to `.vsix`.

**Comment by jamiepratt** [comment]
![Screenshot 2022-11-22 at 09 38 02](https://user-images.githubusercontent.com/558780/203279937-f18a539a-3139-459a-8697-4a196be180c0.png)

Great, I am now seeing links to the see also documentation when the REPL is running too! I'll let you know if I notice any issues with the PR which I am now using.

**Comment by PEZ** [comment]
Thanks for running with this VSIX!

We'll close this once we have released this change.
