### ISSUE TITLE
Expose calva.connect as VSCode API

### ISSUE THREAD

**Issue by orestis** [BetterThanTomorrow/calva#1984]
With Joyride, I could create my own quick-tasks that connect to project-specific REPLs e.g. a production REPL via an SSH tunnel that is always at the same port, or picking a shadow-cljs build all the time, without needing to discover a CLJS configuration. (I always pick `:main`).

Imagined API:

```
await (vscode/commands.executeCommand "calva.connect" "localhost:6666")
;; or perhaps to auto-discover? But I would probably expose the auto-discovery in its own API
await (vscode/commands.executeCommand "calva.connect" #js {:type "shadow-cljs" :build ":main"}})
(vscode/commands.executeCommand "calva.connect" #js {:type "shadow-cljs" :build ":main"}})
```

Of course it could be a part of Calva's Extension API proper, perhaps at the `repl` module?

```
(calva/repl.connect "localhost:6666")
```

I'm not sure I understand how to connect to a CLJS repl so please ignore my API suggestions :)

**Comment by PEZ** [comment]
I think the API suggested is pretty good. We'll see where we end up, but we do have the [custom repl connect sequences](https://calva.io/connect-sequences/) already, looking pretty similar to the map you speculate about there. So an API (proper or via command) that would allow a connect sequence as an argument might make sense. Possibly such a sequence should have entries for host and port.

Without having given it a ton of thought, I am thinking a command would be good, because then you don't need to use Joyride to access it. You can create a keybinding directly, providing the sequence.

**Comment by orestis** [comment]
True! An API could be provided to access the "inference" logic (e.g. given a `shadow-cljs` connection type, return me the string `localhost:12345`).

If the connection command returns a Promise, then it could also be chained with the `executeCode` API:

* Connect to some random REPL
* ...wait for connection to be established...
* Send some code snippet (e.g. to start a remote debugging session etc)

**Comment by PEZ** [comment]
Indeed. I don't remember right now if this is async or sync in Calva, but the scheme can be implemented either way from the consumer's perspective. (My guess is that it is async, because that's what we use in the nREPL client.)

**Comment by PEZ** [comment]
I went for a minimal addressing of this as a first step, @orestis. This PR has it:

* https://github.com/BetterThanTomorrow/calva/pull/2102

It makes the connect command take two arguments. Can be used like so from Joyride:

```clojure
(vscode/commands.executeCommand "calva.connect" "localhost" "54798")
```

Please give it a spin!

Note that you might not need this now, because that PR makes Calva by default not prompt for the port if the port file exists, and also adds config for surpressing other connect/jack-in menus. But anyway. 😄
