### ISSUE TITLE
Setting calva.testOnSave broken: no tests found

### ISSUE THREAD

**Issue by TuggyNE** [BetterThanTomorrow/calva#2005]
It can't find tests anymore when saving the main code file. Saving the test file itself runs the tests fine, though. This worked in 2.0.319; it might have broken in https://github.com/BetterThanTomorrow/calva/commit/07add0b4f3dde630931c38c33fe286fad87e4db4.

Since the use case for this is to automatically run tests when changes are made to the code that needs testing, this should work.

**Comment by bpringe** [comment]
Thanks for reporting. I've confirmed that this works in 2.0.319 and also found that it doesn't work in 3.0.320 (don't know if you were implying that).

**Comment by bpringe** [comment]
I've found that reversing [this change](https://github.com/BetterThanTomorrow/calva/pull/1983/commits/d2a0d9595f1a8894c4892c3f3d424c2a601b8f5b) results in test on save working (sort of) again, but then the problem that change fixes happens again: all tests are run instead of just the namespace tests.
