### ISSUE TITLE
Option for auto selecting a project

### ISSUE THREAD

**Issue by furkan3ayraktar** [BetterThanTomorrow/calva#2094]
### Motivation 💪
Starting a REPL with a single command, without any configuration to learn, is an excellent value for someone jumping on an existing project, exploring an example project for a concept or library, or getting started with Clojure.

### Background 👍
The `replConnectSequences` option allows us to define everything needed to start a REPL on a specific project so that the developer can just run the Jack-In command in Calva and get a running REPL immediately.

Additionally, Calva allows auto-selecting the custom sequences defined within the `replConnectSequences` with the `calva.autoSelectReplConnectProjectType` option. However, if you work in a mono repo, there is another step before project type selection: `Project Selection`.

### Suggestion 💡
It would be great to auto-select a project for the Jack-In command. It could follow the same naming scheme as the project type selection: `calva.autoSelectReplConnectProjectSelection`. Then, I could set it to the `Workspace Root` (or any other project within the mono repo), and just running one single command, the Jack-In command, will be enough to get a REPL!

```jsonc
{
    "calva.autoOpenJackInTerminal": true,
    "calva.autoSelectReplConnectProjectType": "My Favorite Seq",
    "calva.autoSelectReplConnectProjectSelection": "Workspace Root", // <-- Suggested option
    "calva.replConnectSequences": [
        {
            "name": "My Favorite Seq",
            ...   
        }
    ]
}
```

> PS: Having this option would let me remove the last step [here](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app#start-a-repl-in-vscode--calva) and allow people quickly get a Polylith REPL.

**Comment by PEZ** [comment]
Thanks for this suggestion!

Before we go ahead builing on the new `calva.autoSelectReplConnectProjectType` model... I've been thinking a bit about it, and wonder if maybe we were a bit quick in selecting how that option should be provided. Here are two alternatives:

1. Bake it into the `replConnectSequences`. A config something like `autoSelect` there would make Calva skip the menu. Calva used to have a similar behaviour, when there was only one connect sequence, we would auto-select it.
2. Add arguments to the connect and jack-in command, so that they could accept an object with `{autoSelectDefaults: true}`. This would make Calva auto-select any default values, and prompt if there are none (like the first time jack-in is run in a workspace).
   * Resetting defaults would be a matter of running the regular Connect or Jack-in commands.
   * We could provide separate commands that provide this argument with default keyboard shortcut (maybe `ctrl+alt+c c` and `ctrl+alt+c j`) as well.
3. A combination of the two above, where the connect sequence would have a config of `default`, overriding the ”remember last selected” behaviour of the menu. And if the special auto-defaults command is used, it would skip presenting the menu.

If we go for the first option, you would also configure the project root in the connect sequence. If we go for the second option we would automatically also address the project root selection.

Option 1 has the drawback of being more to configure, as well as us having to deprecate a shipped setting. (It's very new, though, so if it should be done, it is now.) A benefit is that the workspace can be preconfigured to not ask first time devs of it to start with providing the defaults. Good for your starter project there, @furkan3ayraktar.

Option 2 has the drawback of being more commands to remember for the user, and not being as fully pre-configurable.  A benefit is the flexibility and maintained user control.

There are probably more options as well as more pros and cons with the ones I have presented here.

WDYT? Pinging in @bpringe, @Cyrik, @SillyCoon, and @julienvincent as well. I think the choice of path here is important.

**Comment by bpringe** [comment]
Option 1 seems to be the simplest option to me and also seems it would require less maintenance and documentation, and probably would be easier for users to understand and less for them to think about.

**Comment by Cyrik** [comment]
I agree with @bpringe on the reasoning. I'm just a bit hesitant to add more things to the ConnectSequence, since it's pretty complex anyway. Not sure if many users actually feel like they can change it.
So maybe solution 3 would give us the best of both worlds?

**Comment by bpringe** [comment]
@PEZ Can you elaborate more on solution 3, running through how it would work step by step?

**Comment by PEZ** [comment]
Let's see...

I was thinking that the sequence would allow a config like `default` and if this is set to `true`, it would always be pre-selected in the project type menu. (Which otherwise remembers the last option as many of our quick-picks do.)

Together with the commands which use `autoSelectDefaults: true` this would take care of #2049 in a better way (imo, I think spreading these settings outside the connect sequences gets confusing). 

The sequence would then also have a configuration for which Project root it goes with. Taking care of the feature suggested in this issue. This makes sense anyway, a custom connect sequence seldom works across several projects.

Classic Jack-in would now be a matter of doing `ctrl+alt+c ctrl+alt+j enter`, where the `enter` would be for selecting the default project type (which is the first connect sequence marked as `default`).

Jacking in via the `autoSelectDefaults` command would be `ctrl+alt+c j`, because we don't need to do `enter` in the project types menu, which would not be presented. Connecting to a running REPL would be `ctrl+alt+c c`, because to deliver on the promise to auto-select defaults, we would auto-select the `host:port` prompt if it is prefilled, which it most often is.

The second set of connect/jack-in commands is probably not something most users would care to learn about, but to anyone wondering if they can get rid of the prompts, the docs would mention this. The real benefit is for projects which has custom connect sequences preconfigured and usage docs guiding the user how to connect the REPl. So in @furkan3ayraktar's case the instructions would be:

> 1. Use the command **Calva: Start a Project REPL and Connect (aka Jack-in), using defaults**.
>
>    \<pretty pic of the Command Palette\>
>    
>    Wait a second for the REPL to start and be connected.

When we go for implementing #1464, even that step could be removed. Even if it might not be advisable to configure an example project like that, idk.

**Comment by PEZ** [comment]
For ClojureScript projects it would offer an alternative to configuring `menuSelections`. Because selecting builds and such once, would then be auto-selected next time the (new) commands are used. And to reset these selections, you would use the classic jack-in/connect commands.

**Comment by PEZ** [comment]
@furkan3ayraktar please feel invited to test this build of Calva: https://output.circle-artifacts.com/output/job/c7579c6c-7f78-4c00-b875-f20d44d4d3f8/artifacts/0/tmp/artifacts/calva-2.0.336-2094-auto-select-project-root-75154dd8.vsix

See
* #2102 for some brief descripton
* [updated Connect Sequence docs](https://github.com/BetterThanTomorrow/calva/blob/2094-auto-select-project-root/docs/site/connect-sequences.md)

**Comment by PEZ** [comment]
I filed a PR on the Polylith Real World example that utilizes this setup:

* https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/pull/29

**Comment by furkan3ayraktar** [comment]
This is great! Thank you, @PEZ; I'll look into the PR on the Polylith example project,
