### ISSUE TITLE
Mac keyboard shortcut

### ISSUE THREAD

**Issue by svdo** [BetterThanTomorrow/calva#213]
Hi,

This issue is quite Mac-specific. On a Mac by default special characters are created by using the OPTION key with a specific other key, and then pressing the key to which it should apply. For example: OPTION-u (for umlaut) followed by an e gives ë. And OPTION-e (for "accent aigu", the acute accent) followed by an i gives í.

The problem is that Calva binds the command "Send current form (or selection) to REPL and evaluate it" to CTRL-OPTION-c followed by OPTION-e. But OPTION-e is the (dead) key for the acute accent, so the accent ends up added to the source code (or even replace the selection if you had one).

I'm not sure what the best solution is. Maybe CTRL-OPTION-c followed by CTRL-OPTION-e? I don't know how vscode handles that, but maybe you could in that case even hold down CTRL-OPTION while typing c and e one after another?

Just for context, #74 was a similar issue.

Thanks again for awesome Calva!

**Comment by svdo** [comment]
Writing that I figured that I could probably try by rebinding the keyboard shortcut in vscode, and indeed when choosing CTRL-OPTION-C followed by CTRL-OPTION-E I don't need to lift CTRL and OPTION between the C and E.

So rebinding this is a fine work-around for me, but still it may be good reconsidering the default shortcut for this command.

**Comment by PEZ** [comment]
It is language dependent as well. I am on a Mac, using Swedish keyboard settings, and the dead key for accent aigu is on another key (not a letter key). Figuring out default keybindings that work across the board is going to a bit impossible. This should probably be fixed on the VS Code level, it is a bit silly that it both performs the keybinding command and produces the output...

We should, however, try to front this keybinding issue a bit in the README and maybe elsewhere, so that people quickly find out about rebinding keys that doesn't work so well for them. Feel invited to create a page about keyboard bindings on the wiki. ❤️ (I just pushed a change to the README that promotes browsing the wiki.)

**Comment by svdo** [comment]
Good idea, will do!

**Comment by svdo** [comment]
Happy with this? https://github.com/BetterThanTomorrow/calva/wiki/Keybinding-conflicts

Please feel free to edit it any way you like of course. :)
