### ISSUE TITLE
Feature Request: Find references/usage

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#215]
Implement the **Find References** API.

Without it we are left with crude text search, **Find in Project**.

For implementing this. Probably [refactor-nrepl](https://github.com/clojure-emacs/refactor-nrepl) is where to turn for the heavy lifting.

**Comment by stigi** [comment]
I was looking for this feature request under "Show Usages" or "Find Usages". Those are the terms used in [Cursive](https://cursive-ide.com/userguide/navigation.html#show-usages). This comment should help the next me to find this issue.

**Comment by matdurand** [comment]
This project seems promising to implement basic refactoring features: https://github.com/snoe/clojure-lsp

**Comment by bpringe** [comment]
Thanks for the link @matdurand. clojure-lsp is something we've been wanting to add for some time. It involves a bit more work than adding refactor-nrepl. There's a PR where this was started at #572. This is something I look forward to the most for Calva's future.

@pez Do you think it would be worth using clojure-lsp for finding references/usages instead of refactor-nrepl? I know refactor-nrepl would be easier to add, but I feel that if we plan to add clojure-lsp, we'd only duplicate work by adding these features with refactor-nrepl, then changing to clojure-lsp later.
