### ISSUE TITLE
copying from the editor

### ISSUE THREAD

**Issue by johnjelinek** [BetterThanTomorrow/calva#219]
![Image 2019-06-11 at 7 06 40 PM](https://user-images.githubusercontent.com/873610/59314717-29679b80-8c7c-11e9-9ae1-04efc796cb51.png)
How do I capture the text as the result here inline within the editor window? If I execute this again and send it to the repl, it'll be a different value. I want to get it on my clipboard.

**Comment by PEZ** [comment]
Hi there! There are two ways to do this. 
1. Copy it from the **Calva says** output pane. Everything that you evaluate inline also gets printed there.
2. Use the **Copy last evaluation results** command, `ctrl+alt+c ctrl+c`.
I prefer the latter, because I don't need to use the mouse and select and stuff.

I now created a page on the wiki about evaluation and included this excellent question there: https://github.com/BetterThanTomorrow/calva/wiki/Code-Evaluation-Tips
