### ISSUE TITLE
"Tab-format" vs "Format document" format rich comments differently

### ISSUE THREAD

**Issue by oyarsa** [BetterThanTomorrow/calva#2205]
Using `Tab`  to format code inside `comment` puts the closing parenthesis on its own line. using `Format document` formats `comment` as any other form, i.e. it puts the closing parenthesis on the same line as the others.

Original code:
```clojure
(comment)
```

After `Tab`:
```clojure
(comment
  )
```

After `Format document`:
```clojure
(comment)
```

I have ` "calva.fmt.keepCommentTrailParenOnOwnLine": true` on my config.

The main issue with this is that I like "format on save, " which means adopting the latter behaviour.

I apologise if this behaviour is documented somewhere. I read the documentation and looked for issues here, and didn't find anything.

**Comment by PEZ** [comment]
Hi! Yes, this is by design. Not sure it is the best design choice, but anyway.

What I do when I want to keep the rich comment ”open” is that I place the keyword `:rcf` before the closing paren: 

```clojure
(comment
  |
  :rcf)
```

Calva's command for creating a Rich Comment form will actually create a form like that.

You'll find some more info about this here: https://calva.io/rich-comments/#special-formatting

**Comment by oyarsa** [comment]
Oh, I missed that page. Thanks for referring to it. I was adding a comment like this:

```clojure
(comment
  ;
  )
```

Is `:rcf` idiomatic, or just something that you do?

**Comment by PEZ** [comment]
> Is `:rcf` idiomatic, or just something that you do?

It is something I have seen others do. And it is something Calva does if you ask it to create a rich comment form, so I guess we might see more of those in the wild.

I've seen your trick too, although placing `#_` before the closing bracket might be more common. And I've also seen `,` there. Both `#_` and `,` are a bit problematic, because for the former, some linters/structural editors don't like it, and for the latter Calva's formatter removes commas, as will many other formatters do. Your trick is not problematic, although it might consume a bit more lines than some people like?

**Comment by PEZ** [comment]
> Oh, I missed that page

We might be missing some cross references to that page...
