### ISSUE TITLE
Difference between regular formatting and formatting with alignment

### ISSUE THREAD

**Issue by isacjunior** [BetterThanTomorrow/calva#2289]
I use `clojure-lsp` and I noticed a difference between commands. 
`Calva Format: Format Current Form` - Works perfectly
`Calva Format: Format and Align Current Form` - Doesn't format using cljfmt from clojure-lsp config

Useful information
`lsp.config.edn` contains the `:legacy/merge-indents? true`

```
Calva version used: v2.0.386
clojure-lsp version used: 2023.08.06-00.28.06
clj-kondo version used: 2023.07.14-SNAPSHOT
```

**Comment by PEZ** [comment]
Thanks! It's a regression since we moved to latest cljfmt for the regular formatting, where the configuration semantics has been changed. The alignment formatting is still using a very old version of cljfmt and thus the old configuration. I forgot about this when upgrading. Will fix!

FYI, it probably has nothing to do with clojure-lsp.
