### ISSUE TITLE
Connecting to an external REPL does not work when local nrepl port exists

### ISSUE THREAD

**Issue by punit-naik** [BetterThanTomorrow/calva#2303]
If the `.nrepl-port` file is populated, while connecting to an external REPL, the prompt to pass external REPL's port does not pop up and calva directly connects to the nREPL port from the `.nrepl-port` file.

Steps to reproduce:
1. Populate the `.nrepl-port` file with some random port
2. Try connecting to an external REPL

**Comment by bpringe** [comment]
@PEZ What's the expected behavior in this case?

Also, I noticed I don't see that file mentioned in the docs. Should we add some info about it there?

**Comment by PEZ** [comment]
The expected behaviour is that Calva should ask for the nrepl port. We could pre-populate with the port number from `.nrepl-port`, maybe, but at least the user needs a way to change the port number. Most often the port file is written by some unrelated nREPL server.

I guess that where we talk about standalone connect we could mention that Calva looks for port files (based on connect sequence) and pre-populates the connect prompt.

**Comment by bpringe** [comment]
> The expected behaviour is that Calva should ask for the nrepl port.

So this is a bug? I'll mark it as such, but remove the tag if I'm wrong.

**Comment by PEZ** [comment]
Yeah, we can call it a bug. 😄 It's an unhandled special case.
