### ISSUE TITLE
Command to run tests for namespace uses user and user-test namespaces when cursor is in ns form

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#2309]
While running some tests in a work project I noticed Calva was saying no tests were found, but for the `user` and `user-test` namespaces. After investigating I found that if my cursor is inside the `ns` form, the issue occurs, but if the cursor is even right before or after (but outside) the `ns` form, the namespaces for the test file and its implementation file are used, as expected.

**Comment by PEZ** [comment]
I'm labeling it as a regression, because I bet it was introduced when we changed the `ns` form discovery a few releases back. Should be easy to expose by adding a failing test here: https://github.com/BetterThanTomorrow/calva/blob/48409c7c656b3b1fffb1e17f997cbad70adc87d5/src/extension-test/unit/util/ns-form-test.ts
