### ISSUE TITLE
[Feature request] Be able to replace the new repl window with a normal leiningen/Clojure repl

### ISSUE THREAD

**Issue by AlexVPopov** [BetterThanTomorrow/calva#231]
It'd be nice, if one could opt-out of using the new repl window and be able to execute Calva commands, such as `Load current namespace`, against a normal leiningen repl. I see the flow roughly like this:

1. Start a repl in a terminal: `lein repl`.
2. Inside VS Code conenct Calva to the running repl.
3. When executing the commands, one could see the result in the repl, started in step 1.

**Comment by PEZ** [comment]
Thanks. To clarify some:

* Step 1 and 2 are already supported. (Even if it is my recommendation that you instead let Calva start the repl for you.)
* Opting out of the REPL window is as easy as closing it.

Certainly, step 3 could get some support. I know how to do it, because that is how Calva used to work. But, it'll take a while before I can prioritize it, I think.
