### ISSUE TITLE
Can't use loaded namespaces in the REPL window

### ISSUE THREAD

**Issue by felixlinker** [BetterThanTomorrow/calva#232]
When I load a namespace via `Ctrl+Alt+C, Enter` the symbols defined in that namespace are not accessible. I have a screenshot attached that illustrates the problem. I tried to reproduce the problem in an already existing workspace by doing the following:
1. Be jacked-in
2. Close current REPL window and open a new one via `Ctrl+Alt+C, Ctrl+Alt+C`
3. Create `./dev-resources/x.clj` with the content that's visible
4. `Ctrl+Alt+C, Enter` with `x.clj` in focus
5. Check that `Calva says` output looks good
6. Type `plus` into the REPL window - doesn't work

![image](https://user-images.githubusercontent.com/9728715/59851300-9100a380-936c-11e9-812f-e85bc8f9c8a1.png)

If I do `(use 'x)`, I can reference `plus` in the REPL window. Also, after having `use`-d the namespace `x`, `Ctrl+Alt+C, Enter` will reload changes to the namespace just fine.

**Comment by felixlinker** [comment]
Additionally, new bindings don't get imported when I do `Ctrl+Alt+C, Enter`. I have to do `(use 'x :reload)` in order to be able to use them.

**Comment by PEZ** [comment]
The file and the repl window use different repl sessions. Sessions are somewhat isolated from each other. They don't share dynamic variables, for instance. That means that the notion of the current namespace differs between the repl backing the repl window and the one backing the files. (The dynamic variable`*ns*` is not shared between these repl sessions.)

I think this is what confuses the situation for you. You can see it on the repl prompt, which says `user=>`, because it's current namespace is `user`. In that namespace, `plus` is not defined. There is a separate command for loading the namespace of the file and switch current namespace in the repl window: **Calva: Load current namespace in REPL window**, `ctrl+alt+c ctrl+alt+n`. You should see the prompt change to `x=>`.

Try it and let me know how it works.

**Comment by felixlinker** [comment]
Switching namespaces with the keystrokes dedicated to that command works just fine!
