### ISSUE TITLE
Replace Current Form (or Selection) with Pretty Printed Form also sorts map entries alphabetically by key

### ISSUE THREAD

**Issue by lsolbach** [BetterThanTomorrow/calva#2533]
The complection of formatting and sorting of keys is not desirable (in all cases).
Separate commands for formatting and sorting would be better.

**Comment by PEZ** [comment]
Thanks for reporting! 🙏

**Comment by PEZ** [comment]
I've made three changes, available with latest Calva (v2.0.448):

1. Disabled map sorting for the command by default.
2. Fixed so that we make a full JSON->EDN conversion of the argument that this function accepts, so that now full zprint configuration are available for anyone who wants to cook custom prettyprint-this-form commands via shortcuts or Joyride.
3. [Documented that this command takes this argument and provided an example](https://calva.io/formatting/#3-replace-current-form-or-selection-with-pretty-printed-form)
