### ISSUE TITLE
[Feature request] REPL history and search

### ISSUE THREAD

**Issue by agoldhammer** [BetterThanTomorrow/calva#256]
How about a way to search the REPL history? And also to list the last n
items in the history. Like the bash shell ctrl-r and history commands.
…

**Comment by bpringe** [comment]
Closing this since we can now search in the new repl/output file. Added a note about the history list to #733.

**Comment by gustavobertolino** [comment]
@bpringe what is the command to search for previous run command in the current REPL window?

**Comment by gustavobertolino** [comment]
The only REPL windown available for me using Calva is the output window. I can run clj commands and instructions, but I cannot retrieve previous commands. 

https://ibb.co/hRsTP7q

**Comment by bpringe** [comment]
@gustavobertolino By search I meant `ctrl+f` / search-in-file. We still need to implement retrieving previous commands. I rarely use this feature, since I do most of my dev in the editors, so my "previous" code is right at my cursor. I realize though that some people may prefer the repl window eval history approach, so we should prioritize adding this.
