### ISSUE TITLE
Pretty printing in REPL window is broken

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#292]
Here is a demo using an example from https://clojuredocs.org/clojure.pprint/pprint

To evaluate `big-map` I used `ctrl+enter`, which should pretty print in the REPL window.

![image](https://user-images.githubusercontent.com/12722744/63707920-f4cd9f80-c7e7-11e9-93d1-5c4b35a25d91.png)

This is what the output looks like if I use `clojure.pprint/pprint`.

![image](https://user-images.githubusercontent.com/12722744/63707975-10d14100-c7e8-11e9-88cf-0c40df0691d2.png)

**Comment by PEZ** [comment]
Thanks. We should consider that default thing, for sure.

**Comment by bpringe** [comment]
I've been looking into this issue and I cannot tell why the output is not formatted correctly in the REPL window when pretty printing. I did confirm though that the evaluation is pretty print formatted before it is sent to the REPL window as output (using the example at the top of this issue).

![image](https://user-images.githubusercontent.com/12722744/64134208-b8beaf80-cd90-11e9-9fb5-ed8b45db2020.png)

This is in calva/nrepl/index.ts in the `NReplEvaluation` of the  `eval` function of the `NReplSession`. At this point I get lost and I'm not quite sure what happens between here and when it shows in the REPL window, but it loses the formatting seen in the image above. Is it possible that the REPL window is not outputting line endings correctly? The evaluation result seems to use `\n` for line endings.

**Comment by bpringe** [comment]
Just to continue my findings further, the message is formatted correctly in repl-window.ts, when it gets sent to `this.panel.webview.postMessage`.

![image](https://user-images.githubusercontent.com/12722744/64135349-5d92ba00-cd9c-11e9-86da-33bc14d68571.png)

Any idea why it's not showing correctly in the REPL window? @PEZ

**Comment by PEZ** [comment]
It is very strange. I am so sure I tested this `ctrl+enter` feature when I had added it... Investigating what is going on now.

Thanks for the research. Now I know where to go looking. :smile:

**Comment by PEZ** [comment]
Hokeyyy, so that brought me down into Calva's Clojure lexer, which is a bit of a mystery to me. But I think I did a non-breaking change to it that gives the response renderer what it needs to honor pretty printing (or any newlines in the response).

The problem was that pretty printing adds a space after the newlines. I don't quite understand why, and I think that is new behaviour. But now our Calva lexer tokenizes all newlines into separate tokens.

Now I really am not sure about that non-breaking part, so will need help testing it. Please checkout the #298 PR and let me know how you fare.

**Comment by bpringe** [comment]
Thanks! I'll check it out.

**Comment by bpringe** [comment]
Closing this since it's merged and working fine using `ctrl+enter` to evaluate in the repl window.
