### ISSUE TITLE
confusion about "go to definition"

### ISSUE THREAD

**Issue by kwladyka** [BetterThanTomorrow/calva#304]
![image](https://user-images.githubusercontent.com/3903726/64487267-869dc980-d238-11e9-8f00-fe3b4309f0ad.png)

1) When click "go to definition" there is information "No definition found".
2) So start the REPL. Maybe it will change something. But the same.
3) So evaluate the file and then it work.

Comments:
2) Not obviously to do that.
3) Very not obviously to do that.

Especially when come from Cursive.

Current state:
User get "No definition found" and only this.

Solution:
Message / alert telling it is necessary to do it. Maybe auto evaluate? Not sure about last one.

**Comment by cfehse** [comment]
@kwladyka  

In version 2.0.49 we have change the Message to `Please connect to a REPL to  retrieve information.` 
We have decided against auto evaluating/file loading because this may disturb the workflow for users who do not want this to happen. Although there is an option `Run load-file when opening a new file and on file save` which ensures that any new opened file is loaded. If the file is not loaded the completion/hover can only show data for elements known to the repl.

I am closing this issue for now because it is pretty much fixed.
