### ISSUE TITLE
[Enhancement] Make code more robust in case Jack-in task fails.

### ISSUE THREAD

**Issue by cfehse** [BetterThanTomorrow/calva#367]
The extension should behave more robust, if the Jack-in task fails either initially (e.g. the user selected an invalid project configuration like `Leiningen + shadow-cljs` if the project is only a Leiningen project) or the REPL process ends prematurely (e.g. a Leiningen project is only used for documentation generation and starting a REPL in the project will fail). 
The extension should always return to a usable state - not leaving die UI in the `connecting` state with the `nREPL` button not usable.

**Comment by PEZ** [comment]
Agree! Maybe this too:

The user should be able to abort the jack-in process at any prompt by pressing <kbd>ESC</kbd>. Today, for some of the prompts, Calva doesn't ”listen” to that and just continues. With bad results, since it doesn't have the answer from the prompt.

If this should be in an issue of its own, let me know and I'll file a new issue instead.

**Comment by cfehse** [comment]
@PEZ

Good point! For the first step in the connection sequence I corrected this already. But I will take a look at the following steps as well.

**Comment by cfehse** [comment]
This is fixed in version 2.0.47.
