### ISSUE TITLE
Editor offers to create or update .joker file for Unrecognized macros

### ISSUE THREAD

**Issue by jefffriesen** [BetterThanTomorrow/calva#43]
This page documents pretty well what to do with Joker not recognizing macros: https://github.com/BetterThanTomorrow/calva/wiki/Getting-Started

It would be kind of cool if the editor would offer to create a .joker file with the offending macro. If the .joker file already exists, then it could just update it. 

Not a huge deal and feel free to close it if it's too difficult, but it would be a nice addition.

**Comment by PEZ** [comment]
Seems like really good help to offer.

**Comment by jefffriesen** [comment]
That's funny - what I meant was that the editor could offer to create or update the `.joker` file 😄. I've seen a dialogue with Parinfer that asks if it's ok if Parinfer can reformat your file - that's what I meant by offer.

But - I should have really offered to do it myself! I read somewhere that you're in the middle of updating the codebase to be completely in Clojurescript. I may wait until then before attempting it.

**Comment by PEZ** [comment]
Haha, I actually understood who should be offering what. But, of course, it would be awesome to get help with making Calva offer this help. 🤠

There is currently quite little code involved, since Joker is doing the heavy lifting. Calva mainly does the work of marking up the problems in the code. So should be quite easy to convert to clojurescript.

We are also considering extracting the linter out into its own extension.

**Comment by PEZ** [comment]
Calva is about to start bundling the clj-kondo extension for listing needs. Thumbs up on [this issue](https://github.com/borkdude/clj-kondo.lsp/issues/2) for getting the neat help that is suggested here.
