### ISSUE TITLE
Namespace outline support

### ISSUE THREAD

**Issue by piotr-yuxuan** [BetterThanTomorrow/calva#57]
Hello Peter and Pedro, my name is Piotr ^^

I've been willing to give this awesome project a try, but it looks like the outline doesn't work yet with Clojure(Script) files. What do you think it would take to add outline support to calva?

Thanks

**Comment by PEZ** [comment]
Peter, Pedro and Piotr, haha! 

This depends some on how complete we want the outline to be. There are to basic ways to choose, I think. Either we do it statically, with an AST or something, or dynamically (via nREPL, which I think should be able to help here).

If we do it statically, I would think that [paredit.js](https://github.com/rksm/paredit.js) (being a library that Calva already uses here and there) could be used. It might be a bit tricky to figure out where the symbols are, and maybe we will miss some of them because macros.

Using nREPL is straightforward too, as long as it provides the operations we need.

Would you like to try experiment some with it? Please holler my way in the [#calva-dev channel of the Clojurians Slack](
https://clojurians.slack.com/messages/calva-dev/) and we can find a way to get a chat going.
