### ISSUE TITLE
Support/detect clojurephant for Jack-in 

### ISSUE THREAD

**Issue by ieugen** [BetterThanTomorrow/calva#614]
Hello,

I'm using VS-Code and gradle with clojurephant to develop clojure. It would be great if we could have detection / support for that in calva.

https://clojurephant.dev/clojurephant/ . I don't know how that works with calva but if you point me in the right direction I can document that in one of the issues: 

https://github.com/clojurephant/clojurephant/issues/47

**Comment by bpringe** [comment]
I'm not sure what would be involved in this. @PEZ Might be able to provide more info. I'm not familiar with clojurephant, but if you have some experience using it with Calva since then, maybe you can investigate this a bit. Or if you have some info that might help others use it with Calva as it is now, that would be good to add to the docs.

**Comment by ieugen** [comment]
Thanks @bpringe , 
I am not sure what is the best way to approach this.
I haven't used gradle for clojure work so it's a nice to have feature at the moment.
If I get back on using gradle with clojure I'll consider improving the integration.

**Comment by ajoberstar** [comment]
I just worked on adding this support to CIDER, and will try to do the same for Calva. I've enhanced Clojurephant to support injecting dependencies, so should be pretty doable.
