### ISSUE TITLE
Improve CLJC experience for finding definitions, etc...

### ISSUE THREAD

**Issue by levitanong** [BetterThanTomorrow/calva#665]
Currently in CLJC files, if you need to look up the definition of a thing in `cljs` mode, you have to click a small button at the bottom of the screen to toggle `cljs` mode, then load the current file and its dependencies onto a `cljs` repl.

If you `load current file and dependencies` while having an active cljs repl, but _don't_ activate `cljs` mode, find definition doesn't work as expected.

I think this is a reasonably difficult problem, and the "perfect" solution is unknown. However, we can improve the experience in some way until we figure out that solution: If loading the definition of a file fails, and the file is known to be a cljc file, then we can suggest that the user make sure the file is in `cljs` mode and perhaps an inline button to do so.

**Comment by PEZ** [comment]
Thanks! I agree both that it is a bit difficult to really solve, and that we probably can improve it with some not-all-that-big effort. Also agree that it probably is a good idea to help suggest this potential solution if the evaluation fails.

Let's see what we currently have to work with:

- User documentation 
- Startup/connection messaging
- The toggle clj/cljs command
- The toggle clj/cljs button in the status bar
- The choice of defaulting to the `clj` REPL.

VS Code also has API:s for displaying alert boxes and for adding buttons through what it names ”Code lens", iirc. 

There might be things, I miss, anybody reading this is welcome to chime in.

At the very least, the user docs could have a section about this feature. Since Calva makes it pretty easy to control it, we can as well highlight it better. Also, the error message should be adapted, like suggested in the OP. We could maybe also try ”flash” the toggle button some when the evaluation errors. (Not sure about how feasible or if it is a good thing to do, just tossing up the idea 😄 ).

**Comment by levitanong** [comment]
I like the idea of flashing it! It's not very good UX to have two different buttons do the same thing,  but it's a convenient alternative in the event that flashing isn't possible.

The bottom bar really could use some documentation, as well as which button is a shortcut to opening the repl, what the behavior is when you close the repl buffer and reopen it (it seems to differ from emacs in that the current namespace is reset when you close and open it.)

One way of being "smart" about the choice of REPLs to use is to see which REPL is open, and where both are open, which one did the user last use. When I develop full stack applications, I work on one side at a time, not both. So I only use clj XOR cljs during a session.

**Comment by bpringe** [comment]
I believe this is resolved in version 2.0.137 thanks to clojure-lsp. Please reopen if I'm mistaken.
