### ISSUE TITLE
Format-on-save only works some of the time

### ISSUE THREAD

**Issue by derekchiang** [BetterThanTomorrow/calva#68]
Format-on-save used to work perfectly, but lately for some reason it only works some of the time.  Most times when I save nothing happens, and I have to manually save a couple more times before the formatting actually happens.

Any idea if this may be an issue with calva or if there's something else I should look into?

**Comment by PEZ** [comment]
Hello! Sorry for super late reply. This is due to that Calva is a bit slow on formatting the whole document and that VS Code was at some point changed so that automatic formatting is not carried out when it takes too long. For now the solution is to use the **Format Document** command before saving. I hope to be able to speed up the formatting somehow.

**Comment by PEZ** [comment]
I don't think there is a fix for this really. Closing.
