### ISSUE TITLE
Reintegrate old REPL/add easy "previous line" functionality

### ISSUE THREAD

**Issue by madisoncfallin** [BetterThanTomorrow/calva#733]
Hey folks! I totally appreciate how buggy the old REPL window was but it was a regular part of my workflow. Can you please add a legacy option to continue to use the old REPL? 

The command-line interface was critical to me as a new Clojure dev. I'd grab the previous line and rerun it all the time. If you decide not to reintegrate, can you add that as a keyboard shortcut?

Thanks!

**Comment by PEZ** [comment]
The legacy option is to keep using `v2.0.108`.

We would very much welcome a PR adding history functionality to the new repl window.

**Comment by bpringe** [comment]
@madisoncfallin You may be interested in this doc and the related links at the bottom of it: https://calva.io/try-first/

I used to use the repl window a lot too, until I learned to eval from files and use comment forms, which is much more efficient imo. With this file/comment workflow there's no need to traverse up to a recent form with `alt+up` (for example), because the code is still right there at your cursor, and you just keep editing+eval'ing as you're trying things.

I do agree though that the history functionality is something we should add back in the new output file.

**Comment by bpringe** [comment]
Something to add to this from #256, another history feature request is to show a list of recent history items to choose from.

**Comment by gustavobertolino** [comment]
**`I do agree though that the history functionality is something we should add back in the new output file.`**

Please, give this feature us back, guys!

**Comment by PEZ** [comment]
You are super welcome to provide a PR with this, @gustavobertolino .

**Comment by gustavobertolino** [comment]
I would, but I cannot right now @PEZ . But a change could not be regressive like it. If the new REPL doesn't provide evaluation history, and the old does, why wouldn't you maintain the old REPL as a sort of fallback to this feature?

**Comment by PEZ** [comment]
It is because it is to much of a burden to maintain it. There is some discussion about it here: https://clojureverse.org/t/calva-summer-of-bugs-2020/6303

**Comment by bpringe** [comment]
@gustavobertolino I'm curious as to why you prefer the repl/history development over the rich comment style of development? I used to use the repl window a lot too, but once I tried using editors for editing I haven't gone back to the repl window / command history, because when developing in the editor (using comment forms to play around), my code is always right there at my cursor, no need to traverse a history list of code. I actually had the repl window set to not open on connect, and basically stopped using it altogether.

I'm not saying we shouldn't add the repl history back and I do plan to if someone else doesn't first, I'm just curious of your reasons. If you're just simply used to it and that's all, that's fine too, just asking. :smile:

**Comment by gustavobertolino** [comment]
The keyboard shortcut to grasp the previous command already run (alt + up/down) doesn't work in the new REPL. That's what I meant by taking the evaluation history commands in the new REPL. Actually I meant being able to take previous by a single keyboard shorcut.
