### ISSUE TITLE
Don't require the `alias` key in deps.edn to jack-in

### ISSUE THREAD

**Issue by beders** [BetterThanTomorrow/calva#780]
Right now the minimal deps.edn file to get started looks like this:

```
{ :aliases {}}
```

However, if the key `aliases` is not provided, jack-in fails (the first time).

**Comment by bpringe** [comment]
I have not experienced this myself. I just tested by creating an empty directory, opening it in vs code, creating a deps.edn file in the directory with an empty map, `{}`, and then running jack-in, choosing Clojure CLI, and jack-in succeeds and I can run code in the output/repl window.

I _do_ see, however, that if I delete the contents of deps.edn (so a blank file), then run jack-in, this message appears: 
![image](https://user-images.githubusercontent.com/12722744/92337078-d2599d80-f05b-11ea-92bb-878a4b4a3f7a.png)


Is the above what you did (a blank file)? And in any case is the above message what you mean by jack-in failing (just making sure there's not some other error)?

If the above is not your scenario, can you provide the detailed steps / scenario in which jack-in failed for you? Also what OS are you using?

Either way, we probably should fix Calva to not show that error when the file is empty, because it's misleading.

**Comment by bpringe** [comment]
Just read the slack convo, I also tried `{:paths ["src"]}` in deps.edn, as you mentioned, and jack-in worked with this as well. I'm wondering if it's some system/OS issue.

**Comment by beders** [comment]
This seems to happen only on fresh installations.
After running jack-in successfully, I was able to delete the `alias` key and it was still working.
Where is Calva storing its state?

**Comment by bpringe** [comment]
Fresh install of vs code and Calva, or just Calva? I uninstalled and reinstalled and still could not reproduce with just `:paths`.

State storage in Calva is bit of a mixed bag. We hope to improve that eventually.  Though, I don't think Calva intentionally stores anything related to project files. Maybe @PEZ can provide more info.

**Comment by PEZ** [comment]
We don't save any state about the project files. But we do save state about the user choices made in those jack-in/connect prompts. I haven't checked the code yet, but that is a clue anyway. My guess is that we have an assumption about the `aliases` key being present, that is somehow dodged by the prompt/quick-pick state.

**Comment by beders** [comment]
I'm unable to reproduce it now. New project, new `deps.edn` and jack-in is working fine :(
I guess, you can close this. Thanks for investigating
