### ISSUE TITLE
Improve inline display of large datasets

### ISSUE THREAD

**Issue by jefffriesen** [BetterThanTomorrow/calva#79]
A little Proto-REPL competition here : )

I like inline evaluation of forms but when the results get too big it runs off the screen:
<img width="837" alt="screen shot 2018-10-09 at 9 11 04 am" src="https://user-images.githubusercontent.com/445733/46679026-473ba880-cba3-11e8-9ee2-83b076771fbb.png">

I know it can be pretty printed to the REPL, but it would be nice to be able to see it inline. I don't always have the REPL big enough to functionally view large datasets and even then, pretty printed shows everything instead of an explorable, nested data structure.

Proto REPL shows a nested data structure inline and is really nice:
<img width="631" alt="screen shot 2018-10-09 at 9 05 35 am" src="https://user-images.githubusercontent.com/445733/46678928-ff1c8600-cba2-11e8-84dd-7e7e822a7b38.png">
https://github.com/jasongilman/proto-repl

I think adding this would be a nice addition, along with with ticket: https://github.com/BetterThanTomorrow/calva/issues/63

**Comment by PEZ** [comment]
Yes, ProtoREPL is true inspiration!

I do not think VS Code supports building a UI like that, unfortunately. It was a while since I investigated it, but when I first added the inline evaluation thing the only option seemed to be using those decorators that is currently being used. And those are really just CSS `::after` styling where the results are inserted as `content:`.

But we shouldn't give up that easily. 😄 I'll have another look at the options available and maybe there is some way that brings us closer to the ProtoREPL experience.

**Comment by jefffriesen** [comment]
Yeah - it seems there needs to be better tools to allow arbitrary markup instead of just `::after`. 

This is a vscode github issue to look at: https://github.com/Microsoft/vscode/issues/3220. They are considering it as built-in to vscode. But proto-repl uses Atom Ink which is a 3rd party tool, so maybe there are 3rd party tools in vscode.

On the other hand, vscode already has the "peek" widget. Not sure if that's available to use.
