### ISSUE TITLE
Allow Format on Save

### ISSUE THREAD

**Issue by jefffriesen** [BetterThanTomorrow/calva#797]
Currently code formats with explicit command (control-option-L) or with tab. It would be really nice to format the entire file on save. In theory this should work with the VSCode settings "Format on Save" enabled but @PEZ said that the formatter may be too slow to format before the save kicks in.

**Comment by bpringe** [comment]
As Peter mentioned in Slack, we could get around this speed limitation with VS Code's save by adding a format-file-then-save command. I'd prefer a solution that worked with VS Code's Format on Save, if possible, but would have to explore the problem more before deciding.

**Comment by svdo** [comment]
FYI: I have "format on save" enabled for ages already and never experienced an issue. YMMV :)

**Comment by bpringe** [comment]
Just came across this while working on something else and wanted to note here for later. This may be useful, so long as formatting completes in a reasonable amount of time (maybe this is what Peter was referring to in Slack):

![image](https://user-images.githubusercontent.com/12722744/96911342-96d13200-1455-11eb-8bb4-13d903886835.png)

**Comment by Hamido-san** [comment]
Not sure if this helps anyone but there are 3 important settings in VS Code for it to work:
- text editor / formatting / **editor: format on save** [should be **true**]
- text editor / formatting / **editor: format on save mode** [should be **file**, since _modifications_ mode doesn't play nice with clojure]
- extensions / clava / **clojure>format: enabled** [should be **true** so VS Code can tap into calva-fmt to format clojure files]

I've also been using these for months and format-on-save just works

**Comment by bpringe** [comment]
Thanks for the info!

**Comment by bpringe** [comment]
Closing this as it seems to work fine when I just enabled "Format on save." For anyone having issues, check your settings, and see @Hamido-san's comment above.
