### ISSUE TITLE
Automatically inject cider middleware at jack-in?

### ISSUE THREAD

**Issue by iku000888** [BetterThanTomorrow/calva#8]
Thanks for publishing a very promising VS Code integration!

It would be great if the middleware dependency can be automatically handled a la emacs cider.

[PR in cider that accomplishes it](https://github.com/clojure-emacs/cider/pull/1552/files)

**Comment by PEZ** [comment]
It seems like Calva (the extension) would need to start the REPL in order for the injection to be done. As it is now Calva merely connects to a previously started REPL.

What does your workflow look like?

**Comment by iku000888** [comment]
Thanks for taking a look!

> It seems like Calva (the extension) would need to start the REPL in order for the injection to be done. As it is now Calva merely connects to a previously started REPL.

Yes, cider does start the repl for me via a command called `cider-jack-in`

My typical work flow would be: 
1. Go to a project root with a project.clj or build.boot. 
2. Run cider-jack-in
3. Have a clojure repl connected editor ready

Apart from starting the repl from the editor, sometimes I do connect to an already started repl (via cider-connect) which in this case would require similar manual setup.

**Comment by PEZ** [comment]
Thanks. I probably should support that workflow. And, while at it, do the dependency auto-inject. I don't really like that such a big part of the README is about dependencies. 🤠

No ETA though, I need some good focus hours to get it rightly implemented.

**Comment by bpringe** [comment]
I second this. I think getting the extension to start the repl automatically and connect to it is key for getting more beginners into Clojure (via this extension at least). I previously used a less feature rich extension for Clojure in VS Code that automatically started the repl and connected to it. This helped me quickly get into Clojure when I was just starting out. It would have taken me some time to figure this out otherwise. I think I actually tried Calva in the past, but couldn't easily figure out how to connect the integrated repl (I had a very limited understanding of the repl and leiningen), so I abandoned Calva and went back to the other extension. Later I got tired of the lack of features and came back to Calva with my new knowledge and got it working. I just wanted to illustrate my perspective as a beginner as it may be representative of the average Clojure beginner.

**Comment by slipset** [comment]
I guess that this would let users connect to repls being exposed by `boot` and `clj` as well?

**Comment by PEZ** [comment]
I welcome anyone interested in this feature to join the #calva-dev channel on Clojurians Slack. There you'll find preview builds of Calva where some of this is working and that we need feedback on to get the feature right. 

As for CLJ and Boot. We will definitely try to support CLJ, but Boot will probably have to wait beyond version 1 of this feature. We know too little about it, and it takes quite a lot of time to figure out how to analyze the different project definitions, so Leiningen + CLJ + shadow-cljs will be our main targets for now.

**Comment by KingMob** [comment]
I was looking over the issues and saw this. Isn't it done? Calva does this currently.

**Comment by PEZ** [comment]
Thanks. This should indeed be closed.

Let me know what else funny stuff you find in the issues-box. :smile:
