### ISSUE TITLE
Custom indentation for some functions

### ISSUE THREAD

**Issue by felipethome** [BetterThanTomorrow/calva#80]
With Cursive it is possible to configure the indentation for each function individually. Is it possible to do the same with Calva?

**Comment by PEZ** [comment]
Unfortunately not. Can you share how it is done in Cursive?

The way I would like to support this is to have `clj-fmt` support the metadata hints for indentation, like this issue is asking about: https://github.com/weavejester/cljfmt/issues/49 (Calva uses `clj-fmt` as its formatting engine).

**Comment by felipethome** [comment]
That is a petty. This is a must have feature for me since I need to respect the indentation of the code in the company I work for.

Maybe Cursive has it own implementation to format code:
![cursive](https://user-images.githubusercontent.com/4316501/46745447-70cc0100-cc83-11e8-8bed-3c483d7ff06d.png)

**Comment by PEZ** [comment]
I think I can add the support with a reasonable amount of effort. I'll look
into it, I think it sounds important.

My question about Cursive was about about how the user can configure it.
But it will not matter too much because the options are limited in vs code
anyway. 😀

**Comment by PEZ** [comment]
Is that project you have a Leiningen project, @felipethome ?

I want to know so that I can prioritize the path to fixing this.

**Comment by felipethome** [comment]
Yes! I think right now Cursive only supports Leiningen, though they are starting to have support for deps.edn in the EAP version

**Comment by mseddon** [comment]
Would configuring cljfmt in your lein project work for you? I am currently working on a rework of the ontype formatting for calva, and once the core is in place (hopefully in a week or so due to christmas) I will be adding support for customisation from the project.

**Comment by felipethome** [comment]
I believe it would. The nice thing about adding to project.clj is that other people would automatically use the same indentation configuration.

**Comment by ericdallo** [comment]
+1 for this feature, the possibility to configure custom macros with it owns identation configurations.
c/c @PEZ

**Comment by PEZ** [comment]
Yes, this has been allowed to wait for quite long. A reason that is so is that I had hoped we should have consolidated Calva on the new formatter, but we still have them both.

If anyone feel the urge to fix this, I will be happy to provide some context and pointers into the code. It shouldn't be too hard. Both formatters actually base their indentation on a `clj-fmt` compatible config map. It is mostly a matter of finding a good way for the user to provide the custom config.

**Comment by guillaume** [comment]
yes this is usually spelled in our projects in a `cljfmt` section like so:

```
...
:cljfmt {:indents {timed [[:inner 0]]
                     mocking [[:inner 0]]
                     stubbing [[:inner 0]]
                     report [[:inner 0]]}}
...
```

**Comment by alidcastano** [comment]
@PEZ could there at least be two modes for indentation, one that follows regular lisp indentation others might be used to, and one with less aggressive nesting? lots of devs using vscode come from JS land, and so that sort of formatting is more familiar/appealing 

I particularly like the formatting @tonsky described here: https://www.youtube.com/watch?v=l1b7Da2DnPo (relevant part starts at 42:18)

**Comment by PEZ** [comment]
I am a big fan of that proposal actually. I tried to implement it immediately when he published the blog post, even. However, I ran across a [bug in cljfmt](https://github.com/weavejester/cljfmt/issues/154). The bug is fixed since a long while though, so it can be tried again.

Without making any new promises about this... it really should be fixed. I will have a new look.

**Comment by alidcastano** [comment]
just started learning clojure, and experimenting with alternatives now, starting to realize it's actually a bit tricky to tame indenting given conventional lisp formatting

in javascript if you have an object with multiple keys you might do this:
```
{
  key1: '1'
  key2: '2'
}
```
but that sort of split wouldn't make sense for lisp since all brackets/parentheses would have to be done that way for consistency. so this obviously makes much more sense:
```
{:foo1 '1'
 :foo2 '1'}
```
but when you start to nest values, the indentation gets ugly:
```
{:foo1 {:bar1 '1'
        :bar2 '2'}
 :foo2 '1'}
```

so maybe the rule can be that any values that can be inlined are split into the next line: 
(split values are indented 4 spaces, whereas same level objects are indented 2 spaces)
```
{:foo1 
  {:bar1 '1'
   :bar2 '2'}
 :foo2 '1'}
```


example --- 

here's how current formatting looks like in a file i'm working on 
```
(defn app-root []
  [:> rn/View {:style {:background-color "white"}}
   [:> rn/Text {:style {:font-size 30
                        :font-weight "100"
                        :margin-bottom 20
                        :text-align "center"}}
    "Hello World!"]])
```

here's what it'd look like following above guideline
```
(defn app-root []
  [:> rn/View 
     {:style {:background-color "white"}}
     [:> rn/Text 
       {:style 
         {:font-size 30
          :font-weight "100"
          :margin-bottom 20
          :text-align "center"}}
       "Hello World!"]])

```

or maybe even like this (which results in more lines but is also more readable)
```
(defn app-root []
  [:> 
     rn/View 
     {:style {:background-color "white"}}
     [:> 
       rn/Text 
       {:style 
         {:font-size 30
          :font-weight "100"
          :margin-bottom 20
          :text-align "center"}}
       "Hello World!"]])

```

**Comment by glenjamin** [comment]
I've just caught up on the thread, and I was a little unclear on the latest position.

Is there a way to pass custom function names or rules to `cljfmt` as used by Calva?

**Comment by PEZ** [comment]
There soon will be. Please help test https://github.com/BetterThanTomorrow/calva/pull/546

**Comment by PEZ** [comment]
This is now finally released. Please see: https://calva.readthedocs.io/en/latest/formatting.html

Sorry for the insane delay. And thanks to @nbardiuk for making such a well-thought-through implementation!
