### ISSUE TITLE
CLJ REPL window doesn't open

### ISSUE THREAD

**Issue by tomasalles** [BetterThanTomorrow/calva#839]
Hello,

When I start the REPL and jack-in VSCode opens the output.calva-repl file and not the CLJ REPL .

Any way to fix this?

Here's my VSCode:

Version: 1.50.1
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T14:44:48.716Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.9.2-arch1-1

Regards,
tomasalles

**Comment by PEZ** [comment]
Hello. The `output.calva-repl` is the CLJ REPL. Maybe something else is broken so that it doesn't work?

**Comment by tomasalles** [comment]
Well, I've seen in other users and it opens a windows like this : https://imgur.com/tdclIam 
where you can directly interact with the REPL.
Is that not the supposed behaviour?

**Comment by bpringe** [comment]
That is the old REPL window that has since been removed and replaced by `output.calva-repl`. Using a file for the output and REPL interaction vs the old way (in the image you linked), which was really a web view, opened up more possibilities for functionality. The old REPL window has its limitations and was a big pain to maintain. See [this post on ClojureVerse](https://clojureverse.org/t/calva-summer-of-bugs-2020/6303) for a detailed explanation of this change.
