### ISSUE TITLE
Go to definition support for clojure/java library source 

### ISSUE THREAD

**Issue by practice** [BetterThanTomorrow/calva#86]
As title shows, it would be very convenient if "Go to definition" loads and shows the source code of library function from library dependencies including Clojure itself and even Java library source.

Thanks in advance.

**Comment by PEZ** [comment]
Hello. It is already possible to go to definition of library code, and even Java library code. So not sure if you are experiencing a setup/dependency problem (Calva needs pretty recent nrepl versions to function fully). Or if it is that some Clojure language library code is unreachable that you are addressing. If it is the latter, I do not now the reasons, but can try investigate it.

However, it seems something has moved in vscode because when having went to the definition of some clojure library code, both hover info and go to definition stopped working. I have just released a new version of Calva that wakes that up again. Maybe it even was this bug that you ran into? Please let me know how the latest version works for you.

**Comment by practice** [comment]
Oh! it was my misconfiguration. Sorry for bothering you. Thank you.

**Comment by PEZ** [comment]
Don't be sorry! You helped me find a bug, that was easy to fix. So now, when you have the configuration right, you can browse around the library code.
