### ISSUE TITLE
Jack in, connect to nrepl not working

### ISSUE THREAD

**Issue by taoroalin** [BetterThanTomorrow/calva#865]
Issue Type: <b>Bug</b>

Start a new nrepl server, for example using `lein nrepl`, `lein figwheel`, or whatever. Then when you connect Calva to that nrepl. it will print the error below. The icon on the bottom bar is lit up, but whenever you run anything, nothing happens. This happens with calva jack-in, connect to repl in project, and external repl. I'm mainly using a project based on `lein new reagent` I just made, but it happens on regular lein and shadow-cljs projects for me as well.
![image](https://user-images.githubusercontent.com/23656042/101797358-ef2cc380-3ad7-11eb-93bf-00c9b34e341b.png)

Extension version: 2.0.134
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-10T23:34:32.027Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (6.68GB free)|
|Process Argv|C:\Users\Tao\source\roam-parser --crash-reporter-id fe9320f9-9845-4f16-8352-ff74aabe303d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpringe** [comment]
I cannot reproduce it on my machine thus far. I created a project with `lein new reagent`, ran jackin, and chose the `Leiningen + Legacy Figwheel` option and it started/connected fine.

Regarding that error you got, it seems to be coming from here:
https://github.com/BetterThanTomorrow/calva/blob/c3043c86c12aa9d5c017d911388d2b960b7cf841/src/connector.ts#L83

And it seems that call to `search` that is throwing the error is likely happening somewhere in this function (namely it's closures):
https://github.com/BetterThanTomorrow/calva/blob/c3043c86c12aa9d5c017d911388d2b960b7cf841/src/connector.ts#L194

If you can provide exact repro steps from project creation to error, that may help. Otherwise, you can try to debug this on your machine. This guide can help you there, it's pretty simple: https://github.com/BetterThanTomorrow/calva/wiki/How-to-Hack-on-Calva

**Comment by bpringe** [comment]
More specifically, for debugging it, I would put a breakpoint at each call to `search` in `createCLJSReplType`, and see when the string it's called on is `null` for you, and work backwards from there. I've never seen this before so I think it may be something to do with your environment (or project setup, but it seems your using a normal template).

**Comment by taoroalin** [comment]
Now I'm getting a different error,  `java.lang.IllegalArgumentException: Provided artifact is missing a version: [cider/cider-nrepl0.23.0]` immediately on jack-in. Do you know what this might be?

**Comment by bpringe** [comment]
This looks the same as #768, which unfortunately is unresolved.

**Comment by kstehn** [comment]
@taoroalin could you check if you have this problem also with Calva version 2.0.126?
Right now i have a similar problem but i cant figure out the cause or even how to reproduce this.
But i found out that 2.0.126 was the last version where everything worked pretty much stable.

**Comment by taoroalin** [comment]
Unfortunately that didn't work for me. Rolling back way more than that didn't work either, so it's something else that's changed on my computer, not a change in Calva.

**Comment by bpringe** [comment]
@taoroalin Can you try the latest Calva version (2.0.140) and let us know if jack-in works for you?

**Comment by taoroalin** [comment]
Thank you so much! It works now!
