### ISSUE TITLE
go to definition jumps to inc instead of inc'

### ISSUE THREAD

**Issue by brdloush** [BetterThanTomorrow/calva#884]
Whenever `inc'` is used in the code editor, calva treats it as regular `inc` (without trailing single quote). When mouse-hovering over it, only the part before single quote is gets underlined. The popup window with documentation shows `inc` documentation instead of `inc'`. Finally, when you use `Go to definition` (F12), it opens source code of `inc`.

Interestingly, `Trigger parameter hints` shows correct hints for parameters of `inc'` :+1:

**Comment by PEZ** [comment]
Yes, it is a bit  interesting that we get it right in some cases. 😄 The first (the failing) cases uses the quite crude API vscode has for this, which recognizes words and we then get to respond on the words it sends us. We were missing single quote as a valid word character. It is now being fixed in a PR.

The last (the working) case is using one of our own grammars for Clojure code, which ”knows” a bit more about how to scan for valid Clojure symbols.
