### ISSUE TITLE
Change slurp, barf, forwardSexp and backwardSexp default keyboard shortcuts

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#950]
I know default keyboard shortcuts are a tricky thing to get right, but as we see over time, certain ones repeatedly give new users pain.

One of these is `ctrl+w`, which people are used to closing tabs in browsers, VS Code, and elsewhere. #725 addresses this one.

Others are the ones mentioned in the title, and will be addressed in this issue. After talking with @clyfe about this in Slack, I propose we make the following changes to Calva's default keyboard shortcuts. With the following, note that `.` is on the same key as `<` (looks like left) and `.` is on the same key as `>` (look like right).

`ctrl+alt+.` - slurp sexp forward (no VS Code overlap)
`ctrl+shift+.` - slurp sexp backward (overlaps with Focus Breadcrumbs)
`ctrl+alt+,` - barf sexp forward
`ctrl+shift+,` - barf sexp backward
`ctrl+rightArrow` - forward sexp. This maps to the shortcut people are used to using for navigating forward.
`ctrl+leftArrow` - backward sexp. This maps to the shortcut people are used to using for navigating backward.

Something to consider is the selection commands as well - maybe these could be simplified if the above changes were made. Or we could leave things as is to avoid a cascade of changes.

Anyway, I'm not saying the above changes are best, let's let this issue be a discussion to figure it out.

**Comment by bpringe** [comment]
Let's keep in mind with this, the main issue is that we hog the VS Code default `ctrl+rightArrow` and `ctrl+leftArrow`, and our version isn't even about movement as the VS Code default, but about editing.

**Comment by PEZ** [comment]
Also keep in mind that all keyboards aren't the same. For instance:

> ` .` is on the same key as `<` (looks like left) and `.` is on the same key as `>` (look like right).

Is not true on my keyboard.

**Comment by PEZ** [comment]
Whichever way we turn, a lot of people will think it is the wrong move.

Since changing defaults is quite disruptive for current users I think we should tread carefully. I'm boring and see two options (assuming Linux and Windows can both be called Windows for this purpose).

## Minimum disruption

### Windows

* .Change **slurp/barf** to use `alt+right/left` instead of `ctrl+right/left`.
* Change **grow/shrink selection** to use something else than `ctrl+w`/`ctrl+shift+w`. (Not sure which)

### Mac

Leave things as they are.

## Slight disruption

Rationale: `ctrl+right/left` is bad for **slurp/barf** on Windows because it is by default a word movement. On Mac it is bad because the user needs to [make a System settings change](https://calva.io/quirks/#macos-and-the-slurp-and-barf-keyboard-shortcuts). 

### Windows

* Same as above about **grow/shrink** selection.
* Change **forward/backward sexp** to use `ctrl+right/left`
* Change **select forward/backward sexp** to use `shift+ctrl+right/left`

### Mac

* Change **forward/backward sexp** to use `alt+right/left`
* Change **select forward/backward sexp** to use `shift+alt+right/left`

### Windows + Mac

* Change **slurp/barf** to use `ctrl+alt+right/left`

**Comment by clyfe** [comment]
@PEZ Re: first point "Minimum disruption"

Change slurp/barf to use alt+right/left (instead of ctrl+right/left) has an issue.
You would also need **shift**+alt+right/left for the "left of the cursor" slurp/barf; and that is `editor.action.smartSelect.expand` already.

In the linked #725 shift+alt+right/left was already proposed for `calva.sexpRangeExpansion`, instead ctrl+w.
Noting `editor.action.smartSelect.expand` & `calva.sexpRangeExpansion` already behave surprisingly similar on sexps.

**Comment by PEZ** [comment]
Good catch, @clyfe. Super tricky materia this... We could maybe remove the default bindings for **backward slurp/barf**. I think they are much less used.

**Comment by PEZ** [comment]
Or, take it as a hint to go for the the **slight disruption**.

**Comment by PEZ** [comment]
> Noting editor.action.smartSelect.expand & calva.sexpRangeExpansion already behave surprisingly similar on sexps

Tried this now, and yes, it is very, very similar. A difference I know of is that all Calva's selection commands add to the grow stack, so Calva's shrinking the selection after, say ”select sexp forward”, will work, but not with the vscode built in one.

I think it makes sense to stick to the idea with using the vscode shortcuts for Calva's version, since it behaves so similarly, but Calva's versions are richer/smarter.

**Comment by PEZ** [comment]
I went for **slight disruption** with the PR. Can you try the VSIX, @clyfe ? Testing on Windows is super painful for me. Here's the VSIX: https://10183-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.152-950-paredit-shortcuts-2e69477b.vsix

We'll have to figure a bit if we need some special messaging around the change, but for now the extension is silent about it.

**Comment by clyfe** [comment]
`ctrl+alt+left/right` doesn't work on Ubuntu 20 Gnome!
Cant get this chord entered in "Keyboard Shortcuts" > "Record Keys" either on Ubuntu.

- [x] crl+left/right does paredit move on windows and linux
- [x] ctrl+shift+left/right does paredit selection on windows and linux
- [ ] ctrl+alt+left/right does slurp/barf on on windows **only**

**Comment by clyfe** [comment]
`ctrl+alt+left/right` is [reserved](https://stackoverflow.com/questions/47808160/intellij-idea-ctrlaltleft-shortcut-doesnt-work-in-ubuntu) for workspace change in "horizontal workspace" mode. There are [hoops](https://askubuntu.com/questions/1029588/18-04-ctrlshift-to-change-language/1088572#1088572) to remove it; ideally, I'd say, we'd have ",." based chords here.

**Comment by PEZ** [comment]
Thanks. New VSIX: https://10188-125431277-gh.circle-artifacts.com/0/tmp/artifacts/calva-2.0.152-950-paredit-shortcuts-c29c49e6.vsix

**Comment by clyfe** [comment]
Looks good.

- [x] crl+left/right does paredit move on windows and linux
- [x] ctrl+shift+left/right does paredit selection on windows and linux
- [x] alt+shift+left/right does expand/shrink selection on windows and linux
- [x] ctrl+alt+left/right does slurp/barf on on windows (& with shift on other side)
- [x] ctrl+alt+,/. does slurp/barf on on linux (& with shift on other side)

**Comment by PEZ** [comment]
Thanks!

**Comment by PEZ** [comment]
Updating with the new shortcuts for the affected changes, since Reddit pointed out that they should have been summarized somewhere. (I still don't know where we should have put them, except for at the very least, here.)

* **Grow Selection** is now `shift+alt+right`
* **Shrink Selection** is now `shift+alt+left`
* **Move Sexpr Forward/Backward** is now `ctrl+right/left`
* **Select Sexpr Forward/Backward** is now `shift+ctrl+right/left`
* **Slurp/Barf Forward** is now `ctrl+alt+right/left`
* **Slurp/Barf Backward** is now `shift+ctrl+alt+right/left`

Linux shares the Windows shortcuts, with the exception of that slurp and barf use `.` and `,`, respectively, instead of right and left, so:

* **Slurp/Barf Forward** is now `ctrl+alt+./,`
* **Slurp/Barf Backward** is now `shift+ctrl+alt+./,`

On Mac grow/shrink selection was kept as was before, and then this:

* **Move Sexpr Forward/Backward** is now `alt+right/left`
* **Select Sexpr Forward/Backward** is now `shift+alt+right/left`
* **Slurp/Barf Forward** is now `ctrl+alt+right/left`
* **Slurp/Barf Backward** is now `shift+ctrl+alt+right/left`

(So same slurp/barf as on Windows.)

**Comment by janniks** [comment]
~It seems this interferes with macOS defaults, as discussed [in Slack](https://clojurians-log.clojureverse.org/calva/2021-02-04/1612478998.153100). I just installed fresh and ⌃+right/left on macOS is word-wise navigation while ⌥-right/left does sexp stuff 😬 very confusing... I would love to change it, but that's a ton of keybindings to override manually, considering there is also up/down and a bunch of shift modifiers etc. — would love to see this fixed to defaults as mentioned [here](https://clojurians-log.clojureverse.org/calva/2021-02-04/1612478998.153100)~

**Update**: nevermind, I found the super helpful config option `hijackVSCodeDefaults` (which is `true` by default) at https://github.com/BetterThanTomorrow/calva/issues/1112 Leaving this here for other users with similar troubles: simply add `"calva.paredit.hijackVSCodeDefaults": false,` to your config to keep system defaults.
