### ISSUE TITLE
Text+sexp mixed movements

### ISSUE THREAD

**Issue by clyfe** [BetterThanTomorrow/calva#951]
### Problem Statement

Let `|` be the cursor, and the text/cursor state be: `(foo/bar|`.
If I move `paredit.backwardSexp`  I end up in  `(|foo/bar` state.

**I'd like that to end up in `(foo/|bar` state  in this case.**

Same goes for strings or keywords, not just symbols (any other case?).
Noting `cursorWordLeft` would make precisely the movement described.

I have both these commands mapped to ctrl+left, with backwardSexp taking precedence in paredit mode.
**In other words**, I want ctrl+left to be smart enough to choose between the two, depending on context.

### Potential Solution

Keybinding "when" conditions could be used for this, if extra flags would exist:
`calva:symbolOrKeywordOrStringToTheLeft / Right`
`calva:inSymbolOrKeywordOrString`

```js
{
        "key": "ctrl+left",
        "command": "paredit.backwardSexp",
        "when": "... paredit:keyMap =~ /original|strict/ 
                     && !calva:symbolOrKeywordOrStringToTheLeft
                     && !calva:inSymbolOrKeywordOrString"
}
```

**Comment by bpringe** [comment]
It seems unnecessarily complex to add this kind of conditional logic for the same shortcut/action. I also think the paredit commands should always do the same thing. If this were implemented, I think it would be better to put in the implementation of backwardSexp. That said though, I'd like to keep operations like backwardSexp consistent with how they work elsewhere.

**Comment by PEZ** [comment]
I like the idea of providing more contexts about the current cursor position. We already calculate some of that.

Not sure it will help for the use case though. `cursorWordLeft` skips past the `/` when I try it. And I expect it to, since Calva defines `/` as a `wordCharacter`. This can't really be changed, because that is how vscode finds words for us to provide hovers and stuff. So, this needs to be brought upstream to the vscode team, I think. (Unless I misunderstand the suggestion, of course).

**Comment by clyfe** [comment]
We can also implement a `calva:cursorWordLeft` and fallback to that one. Or: `paredit.backwardSexpOrWord`. Word here meaning "special", not vscode-word-with-the-problem-you-described.

**Comment by PEZ** [comment]
That would require some serious changes to Calva's Clojure grammar, though. The cost/benefit is not in favour.

However, all is not lost. Because, I had it wrong with the `wordCharacter` thing. That is not what determines the movement of `cursorWord[Left|Right]` movement. That is determined by the user controlled `editor.wordSeparator` setting. So if you include `/` in there it will not move past those. Keep in mind that it also affects what is selected at double-click and such too.

I think it makes most sense that Calva's sexp movements keep moving by sexps and that we let VS Code's word movement take care of whatever the user defines as words. Still will consider to add context variables though. That will give the user more power to override decisions we make with Calva defaults. (I interpret your suggestions to be inline with this, so not arguing, just clarifying, here.)

**Comment by livtanong** [comment]
I want to add that the editor.wordSeparator you want to change is in the clojure json settings. If you open up the preferences pane and search for `editor.wordSeparator`, you'll see an Editor: Word Separators section. **this is not the one**. There will be another section that says `[clojure]` with a button to "edit in settings.json". **this is the one**

**Comment by clyfe** [comment]
I'm doing this, at the moment: https://github.com/clyfe/vscode-calva-setup/blob/master/settings.json#L27

```json
"[clojure]": {
    "editor.wordSeparators": "\t ()`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"
},
```

**Comment by clyfe** [comment]
Noting that this ticket is less relevant in strings which calva already treats like lists and one can move inside of.
I closed the ticket because I now do such movements via selection (not ideal) and don't want to burden the maintainers too much.
Hope to come back to this in the future, as time allows.
